/**
 * v183 — چالش‌های آقایان (۱۷ چالش) — الگوی محتوای ثابت جنسیتی
 * همهٔ کاربران آقا (و فقط آن‌ها) این ۱۷ چالش را می‌بینند — رایگان برای همه.
 * برنامهٔ روزانهٔ هر چالش ثابت است (قالب‌های هفتگی چرخشی + پیشرفت هفتگی
 * خودکار) — برنامهٔ «شخصی‌سازی‌شده» محصول پولی فیتاپ است.
 */
import type { ChallengeDef } from "./challenges-data";

export const CHALLENGES_MEN: ChallengeDef[] = [
  {
    slug: "m-sixpack-45",
    gender: "men",
    title: "شکم شش‌تکه ۴۵ روزه",
    tagline: "۴۵ روز، یک شکم متفاوت — کورِ چربی، بیکِ شکم",
    description:
      "محبوب‌ترین چالش فیتاپ! ترکیب هوشمندانهٔ حرکات مرکز بدن و چربی‌سوزی که لایهٔ چربی روی شکم را می‌ترکاند و عضلات شکم را روزبه‌روز برجسته‌تر می‌کند. فقط ۲۵ تا ۳۵ دقیقه در روز می‌خواهد.",
    disciplineLabel: "شکم و چربی‌سوزی",
    difficulty: "intermediate",
    durationDays: 45,
    daysPerWeek: 5,
    minutesPerDay: 30,
    equipment: "بدون تجهیزات (اختیاری: چرخ شکم)",
    cover: "/images/challenges/men/m-sixpack-45.jpg",
    accent: { from: "#f97316", via: "#ea580c", to: "#7c2d12" },
    emoji: "🔥",
    dayTemplates: [
      {
        title: "مرکز بدن و کرانچ",
        focus: "شکم بالا و پایین",
        exercises: [
          { name: "کرانچ شکم (Crunch)", muscle: "شکم", sets: 4, reps: "15-20", restSec: 45, animKey: "Crunch" },
          { name: "بالازدن پا در حالت خوابیده (Leg Raise)", muscle: "شکم پایین", sets: 4, reps: "12-15", restSec: 45, animKey: "Lying Leg Raise" },
          { name: "کرانچ دوچرخه (Bicycle Crunch)", muscle: "شکم", sets: 3, reps: "20-30", restSec: 45, animKey: "Bicycle Crunch" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "40s", restSec: 40, animKey: "Plank" },
          { name: "روسی پیچ (Russian Twist)", muscle: "پهلو", sets: 3, reps: "20-24", restSec: 40, animKey: "Russian Twist" },
        ],
      },
      {
        title: "شکم + چربی‌سوزی",
        focus: "ترکیب هوازی و شکم",
        exercises: [
          { name: "جک پرش (Jumping Jacks)", muscle: "هوازی", sets: 3, reps: "40s", restSec: 30, animKey: "Jumping Jacks" },
          { name: "کوهنورد درجا (Mountain Climbers)", muscle: "شکم و هوازی", sets: 4, reps: "30s", restSec: 40, animKey: "Mountain Climbers" },
          { name: "کرانچ متقاطع (Cross-Body Crunch)", muscle: "شکم و پهلو", sets: 3, reps: "16-20", restSec: 45, animKey: "Cross-Body Crunch" },
          { name: "برپی (Burpee)", muscle: "فول‌بادی", sets: 3, reps: "10-12", restSec: 60, animKey: "Burpee" },
          { name: "پا قیچی خوابیده (Scissor Kicks)", muscle: "شکم پایین", sets: 3, reps: "30s", restSec: 40, animKey: "Scissor Kicks" },
        ],
      },
      {
        title: "مرکز بدن ایستا",
        focus: "ثبات و استقامت شکم",
        exercises: [
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 4, reps: "45s", restSec: 45, animKey: "Plank" },
          { name: "پلانک جانبی (Side Plank)", muscle: "پهلو", sets: 3, reps: "30s", restSec: 40, animKey: "Side Plank" },
          { name: "ددباگ (Dead Bug)", muscle: "مرکز بدن", sets: 3, reps: "12-14", restSec: 40, animKey: "Dead Bug" },
          { name: "پلانک لمس شانه (Shoulder-Tap Plank)", muscle: "مرکز بدن", sets: 3, reps: "16-20", restSec: 40, animKey: "Plank Shoulder Tap" },
          { name: "سوپرمن (Superman Hold)", muscle: "کمر", sets: 3, reps: "30s", restSec: 40, animKey: "Superman" },
        ],
      },
      {
        title: "شکم سنگین (اختیاری: تجهیزات)",
        focus: "مقاومت برای شکم",
        exercises: [
          { name: "رول‌اوت با غلتک شکم (Ab Wheel Rollout)", muscle: "شکم", sets: 4, reps: "8-12", restSec: 60, animKey: "Ab Wheel Rollout" },
          { name: "بالازدن پاها در آویزان (Hanging Leg Raise)", muscle: "شکم پایین", sets: 4, reps: "8-12", restSec: 60, animKey: "Hanging Leg Raise" },
          { name: "کرانچ شکم (Crunch)", muscle: "شکم", sets: 3, reps: "20-25", restSec: 45, animKey: "Crunch" },
          { name: "پل باسن (Glute Bridge)", muscle: "باسن و کمر", sets: 3, reps: "15-20", restSec: 45, animKey: "Glute Bridge" },
          { name: "پلانک پویا (Plank Up-Down)", muscle: "مرکز بدن", sets: 3, reps: "12-16", restSec: 45, animKey: "Plank Up Down" },
        ],
      },
    ],
  },
  {
    slug: "m-shoulders-60",
    gender: "men",
    title: "شانه‌های پهن ۶۰ روزه",
    tagline: "فرم V بخواه؟ شانه بساز — ۶۰ روز مسیرش همین است",
    description:
      "کمربند پهن بالاتنه از شانه ساخته می‌شود! این چالش با پرس‌ها، نشرها و کار کتف، شانه‌هایت را پهن و گرد می‌کند و قاب فیزیک V شکل را روی بدنت نصب می‌کند.",
    disciplineLabel: "فیزیک آقایان",
    difficulty: "intermediate",
    durationDays: 60,
    daysPerWeek: 4,
    minutesPerDay: 45,
    equipment: "دمبل + میلهٔ بارفیکس (یا سیم‌کش)",
    cover: "/images/challenges/men/m-shoulders-60.jpg",
    accent: { from: "#f59e0b", via: "#d97706", to: "#78350f" },
    emoji: "🦅",
    dayTemplates: [
      {
        title: "پرس شانه و نشر",
        focus: "شانه جلو و میانی",
        exercises: [
          { name: "پرس سرشانه دمبل (Dumbbell Shoulder Press)", muscle: "شانه", sets: 4, reps: "10-12", restSec: 75, animKey: "Dumbbell Shoulder Press" },
          { name: "نشر جانب دمبل (Dumbbell Lateral Raise)", muscle: "شانه میانی", sets: 4, reps: "12-15", restSec: 60, animKey: "Dumbbell Lateral Raise" },
          { name: "نشر از جلو دمبل (Dumbbell Front Raise)", muscle: "شانه جلو", sets: 3, reps: "12-15", restSec: 60, animKey: "Dumbbell Front Raise" },
          { name: "فیس‌پول (Face Pull)", muscle: "پشت شانه", sets: 3, reps: "15-20", restSec: 60, animKey: "Face Pull" },
          { name: "شراگ دمبل (Dumbbell Shrug)", muscle: "تراپezius", sets: 3, reps: "12-15", restSec: 60, animKey: "Dumbbell Shrug" },
        ],
      },
      {
        title: "پشت و زیربغل (پهن‌کنندهٔ فرم V)",
        focus: "عرض پشت",
        exercises: [
          { name: "بارفیکس (Pull-Up)", muscle: "زیربغل", sets: 4, reps: "6-10", restSec: 90, animKey: "Pull-Up" },
          { name: "زیربغل سیم‌کش از جلو (Lat Pulldown)", muscle: "زیربغل", sets: 4, reps: "10-12", restSec: 75, animKey: "Lat Pulldown" },
          { name: "زیربغل دمبل تک‌دست (Single-Arm Dumbbell Row)", muscle: "زیربغل", sets: 4, reps: "10-12", restSec: 60, animKey: "Single Arm Dumbbell Row" },
          { name: "اسپرانا (Reverse Fly)", muscle: "پشت شانه", sets: 3, reps: "15-18", restSec: 60, animKey: "Reverse Fly" },
        ],
      },
      {
        title: "سینه + شانه (پمپاژ کامل بالاتنه)",
        focus: "ترکیبی",
        exercises: [
          { name: "پرس سینه دمبل (Dumbbell Bench Press)", muscle: "سینه", sets: 4, reps: "10-12", restSec: 75, animKey: "Dumbbell Bench Press" },
          { name: "پرس سرشانه دمبل (Dumbbell Shoulder Press)", muscle: "شانه", sets: 4, reps: "10-12", restSec: 75, animKey: "Dumbbell Shoulder Press" },
          { name: "شنا دست‌باز (Wide Push-Up)", muscle: "سینه", sets: 3, reps: "12-20", restSec: 60, animKey: "Wide Push-Up" },
          { name: "نشر جانب دمبل (Dumbbell Lateral Raise)", muscle: "شانه میانی", sets: 4, reps: "12-15", restSec: 60, animKey: "Dumbbell Lateral Raise" },
          { name: "بارفیکس (Pull-Up)", muscle: "زیربغل", sets: 3, reps: "6-10", restSec: 90, animKey: "Pull-Up" },
        ],
      },
    ],
  },
  {
    slug: "m-mass-60",
    gender: "men",
    title: "حجم و عضله‌سازی ۶۰ روزه",
    tagline: "وزنه بزن، بخور، بزرگ شو — ۶۰ روز حجم واقعی",
    description:
      "برنامهٔ کلاسیک حجم‌گیری فیتاپ: اسپلیت ۴ تکه، بار تدریجی و تمرکز روی حرکات چندمفصلی. اگر دنبال کیلو اضافه روی بازو، سینه و پشت هستی، این چالش برای تو ساخته شده.",
    disciplineLabel: "بادی‌بیلدینگ",
    difficulty: "advanced",
    durationDays: 60,
    daysPerWeek: 5,
    minutesPerDay: 60,
    equipment: "باشگاه (هالتر/دمبل/دستگاه)",
    cover: "/images/challenges/men/m-mass-60.jpg",
    accent: { from: "#dc2626", via: "#b91c1c", to: "#450a0a" },
    emoji: "💪",
    dayTemplates: [
      {
        title: "سینه و پشت بازو",
        focus: "فشار بالاتنه",
        exercises: [
          { name: "پرس سینه هالتر (Barbell Bench Press)", muscle: "سینه", sets: 4, reps: "8-10", restSec: 90, animKey: "Barbell Bench Press" },
          { name: "پرس سینه دمبل (Dumbbell Bench Press)", muscle: "سینه", sets: 4, reps: "10-12", restSec: 75, animKey: "Dumbbell Bench Press" },
          { name: "شنا دست‌جمع (Diamond Push-Up)", muscle: "سینه داخلی", sets: 3, reps: "12-15", restSec: 60, animKey: "Diamond Push-Up" },
          { name: "پشت بازو سیم‌کش (Triceps Pushdown)", muscle: "پشت بازو", sets: 4, reps: "12-15", restSec: 60, animKey: "Triceps Pushdown" },
          { name: "پشت بازو دمبل جفت دست (Overhead Dumbbell Extension)", muscle: "پشت بازو", sets: 3, reps: "10-12", restSec: 60, animKey: "Overhead Triceps Extension" },
        ],
      },
      {
        title: "پشت و جلو بازو",
        focus: "کشش بالاتنه",
        exercises: [
          { name: "ددل‌لیفت هالتر (Barbell Deadlift)", muscle: "پشت", sets: 4, reps: "6-8", restSec: 120, animKey: "Barbell Deadlift" },
          { name: "زیربغل هالتر خم (Bent-Over Barbell Row)", muscle: "زیربغل", sets: 4, reps: "8-10", restSec: 90, animKey: "Bent Over Barbell Row" },
          { name: "زیربغل سیم‌کش از جلو (Lat Pulldown)", muscle: "زیربغل", sets: 3, reps: "10-12", restSec: 75, animKey: "Lat Pulldown" },
          { name: "جلو بازو هالتر (Barbell Bicep Curl)", muscle: "جلو بازو", sets: 4, reps: "10-12", restSec: 60, animKey: "Barbell Bicep Curl" },
          { name: "چکشی جلو بازو (Hammer Curl)", muscle: "بازو و ساعد", sets: 3, reps: "10-12", restSec: 60, animKey: "Hammer Curl" },
        ],
      },
      {
        title: "پا و مرکز بدن",
        focus: "اندام تحتانی",
        exercises: [
          { name: "اسکوات هالتر (Barbell Back Squat)", muscle: "پا", sets: 4, reps: "8-10", restSec: 120, animKey: "Barbell Back Squat" },
          { name: "ددل‌لیفت رومانیایی (Romanian Deadlift)", muscle: "همسترینگ", sets: 4, reps: "8-10", restSec: 90, animKey: "Romanian Deadlift" },
          { name: "اسکوات بلغاری (Bulgarian Split Squat)", muscle: "پا", sets: 3, reps: "10-12", restSec: 75, animKey: "Bulgarian Split Squat" },
          { name: "ساق پا ایستاده (Standing Calf Raise)", muscle: "ساق", sets: 4, reps: "15-20", restSec: 45, animKey: "Standing Calf Raise" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "45s", restSec: 40, animKey: "Plank" },
        ],
      },
      {
        title: "شانه و بازو (پمپ نهایی)",
        focus: "جزئیات بالاتنه",
        exercises: [
          { name: "پرس سرشانه هالتر (Barbell Shoulder Press)", muscle: "شانه", sets: 4, reps: "8-10", restSec: 90, animKey: "Barbell Shoulder Press" },
          { name: "نشر جانب دمبل (Dumbbell Lateral Raise)", muscle: "شانه میانی", sets: 4, reps: "12-15", restSec: 60, animKey: "Dumbbell Lateral Raise" },
          { name: "اسپرانا (Reverse Fly)", muscle: "پشت شانه", sets: 3, reps: "15-18", restSec: 60, animKey: "Reverse Fly" },
          { name: "جلو بازو دمبل (Dumbbell Bicep Curl)", muscle: "جلو بازو", sets: 4, reps: "10-12", restSec: 60, animKey: "Dumbbell Bicep Curl" },
          { name: "دیپ پارالل (Dips)", muscle: "پشت بازو و سینه", sets: 3, reps: "8-12", restSec: 75, animKey: "Dips" },
        ],
      },
    ],
  },
  {
    slug: "m-classic-45",
    gender: "men",
    title: "فیزیک کلاسیک ۴۵ روزه",
    tagline: "تناسبات طلایی، مثل قهرمانان قدیم",
    description:
      "الهام‌گرفته از فیزیک کلاسیک: کمر پهن، کمر باریک، سینه کامل و پا قوی. ترکیب هوشمند قدرت و فرم‌دهی برای بدنی متوازن و سینمایی.",
    disciplineLabel: "فیزیک کلاسیک",
    difficulty: "intermediate",
    durationDays: 45,
    daysPerWeek: 5,
    minutesPerDay: 55,
    equipment: "باشگاه (هالتر/دمبل/دستگاه)",
    cover: "/images/challenges/men/m-classic-45.jpg",
    accent: { from: "#d97706", via: "#b45309", to: "#451a03" },
    emoji: "🏆",
    dayTemplates: [
      {
        title: "سینه و زیربغل (قاب طلایی)",
        focus: "تناسب بالاتنه",
        exercises: [
          { name: "پرس سینه هالتر (Barbell Bench Press)", muscle: "سینه", sets: 4, reps: "8-10", restSec: 90, animKey: "Barbell Bench Press" },
          { name: "بارفیکس (Pull-Up)", muscle: "زیربغل", sets: 4, reps: "6-10", restSec: 90, animKey: "Pull-Up" },
          { name: "پول‌اُوِر دمبل (Dumbbell Pullover)", muscle: "سینه و زیربغل", sets: 3, reps: "10-12", restSec: 60, animKey: "Dumbbell Pullover" },
          { name: "زیربغل دمبل تک‌دست (Single-Arm Dumbbell Row)", muscle: "زیربغل", sets: 4, reps: "10-12", restSec: 60, animKey: "Single Arm Dumbbell Row" },
          { name: "شنا دست‌باز (Wide Push-Up)", muscle: "سینه", sets: 3, reps: "15-20", restSec: 60, animKey: "Wide Push-Up" },
        ],
      },
      {
        title: "شانه و بازو (پهنای V)",
        focus: "شانه و بازو",
        exercises: [
          { name: "پرس سرشانه دمبل (Dumbbell Shoulder Press)", muscle: "شانه", sets: 4, reps: "10-12", restSec: 75, animKey: "Dumbbell Shoulder Press" },
          { name: "نشر جانب دمبل (Dumbbell Lateral Raise)", muscle: "شانه میانی", sets: 4, reps: "12-15", restSec: 60, animKey: "Dumbbell Lateral Raise" },
          { name: "فیس‌پول (Face Pull)", muscle: "پشت شانه", sets: 3, reps: "15-20", restSec: 60, animKey: "Face Pull" },
          { name: "جلو بازو هالتر (Barbell Bicep Curl)", muscle: "جلو بازو", sets: 4, reps: "10-12", restSec: 60, animKey: "Barbell Bicep Curl" },
          { name: "پشت بازو سیم‌کش (Triceps Pushdown)", muscle: "پشت بازو", sets: 3, reps: "12-15", restSec: 60, animKey: "Triceps Pushdown" },
        ],
      },
      {
        title: "پا و مرکز بدن کلاسیک",
        focus: "پای متناسب",
        exercises: [
          { name: "اسکوات هالتر (Barbell Back Squat)", muscle: "پا", sets: 4, reps: "8-10", restSec: 120, animKey: "Barbell Back Squat" },
          { name: "لانج (Lunge)", muscle: "پا و باسن", sets: 3, reps: "12-14", restSec: 75, animKey: "Lunge" },
          { name: "پل باسن (Glute Bridge)", muscle: "باسن", sets: 3, reps: "15-20", restSec: 60, animKey: "Glute Bridge" },
          { name: "ساق پا ایستاده (Standing Calf Raise)", muscle: "ساق", sets: 4, reps: "15-20", restSec: 45, animKey: "Standing Calf Raise" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "45s", restSec: 40, animKey: "Plank" },
        ],
      },
    ],
  },
  {
    slug: "m-arms-30",
    gender: "men",
    title: "بازوهای فولادی ۳۰ روزه",
    tagline: "۳۰ روز تا بازوهایی که آستین تنگ می‌شود",
    description:
      "چالش تخصصی بازو: جلو بازو، پشت بازو و ساعد با حجم بالا و استراحت کوتاه برای پمپ خون حداکثری. همراه با کار سینه و پشت تا تعادل حفظ شود.",
    disciplineLabel: "بازو",
    difficulty: "intermediate",
    durationDays: 30,
    daysPerWeek: 4,
    minutesPerDay: 35,
    equipment: "دمبل + میلهٔ بارفیکس",
    cover: "/images/challenges/men/m-arms-30.jpg",
    accent: { from: "#ea580c", via: "#c2410c", to: "#431407" },
    emoji: "💪",
    dayTemplates: [
      {
        title: "جلو بازو کامل",
        focus: "بازوی جلویی",
        exercises: [
          { name: "جلو بازو دمبل (Dumbbell Bicep Curl)", muscle: "جلو بازو", sets: 4, reps: "10-12", restSec: 60, animKey: "Dumbbell Bicep Curl" },
          { name: "چکشی جلو بازو (Hammer Curl)", muscle: "بازو و ساعد", sets: 4, reps: "10-12", restSec: 60, animKey: "Hammer Curl" },
          { name: "بارفیکس (Pull-Up)", muscle: "زیربغل و بازو", sets: 3, reps: "6-10", restSec: 90, animKey: "Pull-Up" },
          { name: "شنا دست‌جمع (Diamond Push-Up)", muscle: "پشت بازو", sets: 3, reps: "12-15", restSec: 60, animKey: "Diamond Push-Up" },
        ],
      },
      {
        title: "پشت بازو کامل",
        focus: "بازوی پشتی",
        exercises: [
          { name: "پشت بازو سیم‌کش (Triceps Pushdown)", muscle: "پشت بازو", sets: 4, reps: "12-15", restSec: 60, animKey: "Triceps Pushdown" },
          { name: "پشت بازو دمبل جفت دست (Overhead Dumbbell Extension)", muscle: "پشت بازو", sets: 4, reps: "10-12", restSec: 60, animKey: "Overhead Triceps Extension" },
          { name: "دیپ پارالل (Dips)", muscle: "پشت بازو و سینه", sets: 3, reps: "8-12", restSec: 75, animKey: "Dips" },
          { name: "شنا (Push-Up)", muscle: "سینه و بازو", sets: 3, reps: "15-20", restSec: 60, animKey: "Push-Up" },
        ],
      },
      {
        title: "پمپ ترکیبی بازو",
        focus: "جلو + پشت بازو",
        exercises: [
          { name: "جلو بازو هالتر (Barbell Bicep Curl)", muscle: "جلو بازو", sets: 4, reps: "10-12", restSec: 60, animKey: "Barbell Bicep Curl" },
          { name: "پشت بازو دمبل جفت دست (Overhead Dumbbell Extension)", muscle: "پشت بازو", sets: 4, reps: "12-15", restSec: 60, animKey: "Overhead Triceps Extension" },
          { name: "چکشی جلو بازو (Hammer Curl)", muscle: "بازو و ساعد", sets: 3, reps: "12-15", restSec: 60, animKey: "Hammer Curl" },
          { name: "شنا دست‌جمع (Diamond Push-Up)", muscle: "پشت بازو", sets: 3, reps: "12-15", restSec: 60, animKey: "Diamond Push-Up" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "40s", restSec: 40, animKey: "Plank" },
        ],
      },
    ],
  },
  {
    slug: "m-chest-30",
    gender: "men",
    title: "سینه تیتانیومی ۳۰ روزه",
    tagline: "۳۰ روز، سینه‌ای که تی‌شرت را پر می‌کند",
    description:
      "تمرکز کامل روی سینه از زاویه‌های مختلف: پرس‌های سنگین برای تودهٔ عضلانی و شناها و حرکات تک‌مفصلی برای فرم و خطوط سینه.",
    disciplineLabel: "سینه",
    difficulty: "intermediate",
    durationDays: 30,
    daysPerWeek: 4,
    minutesPerDay: 40,
    equipment: "دمبل + میله (یا باشگاه)",
    cover: "/images/challenges/men/m-chest-30.jpg",
    accent: { from: "#f97316", via: "#c2410c", to: "#431407" },
    emoji: "🛡️",
    dayTemplates: [
      {
        title: "پرس سینه سنگین",
        focus: "تودهٔ سینه",
        exercises: [
          { name: "پرس سینه هالتر (Barbell Bench Press)", muscle: "سینه", sets: 4, reps: "8-10", restSec: 90, animKey: "Barbell Bench Press" },
          { name: "پرس سینه دمبل (Dumbbell Bench Press)", muscle: "سینه", sets: 4, reps: "10-12", restSec: 75, animKey: "Dumbbell Bench Press" },
          { name: "شنا دست‌باز (Wide Push-Up)", muscle: "سینه بیرونی", sets: 3, reps: "12-18", restSec: 60, animKey: "Wide Push-Up" },
          { name: "دیپ پارالل (Dips)", muscle: "سینه پایین", sets: 3, reps: "8-12", restSec: 75, animKey: "Dips" },
        ],
      },
      {
        title: "سینه با وزن بدن",
        focus: "فرم و استقامت",
        exercises: [
          { name: "شنا (Push-Up)", muscle: "سینه", sets: 4, reps: "15-20", restSec: 60, animKey: "Push-Up" },
          { name: "شنا دست‌جمع (Diamond Push-Up)", muscle: "سینه داخلی", sets: 3, reps: "12-15", restSec: 60, animKey: "Diamond Push-Up" },
          { name: "شنا بالاسینه (Incline Push-Up)", muscle: "سینه بالا", sets: 3, reps: "12-18", restSec: 60, animKey: "Incline Push-Up" },
          { name: "شنا فضانورد (Archer Push-Up)", muscle: "سینه", sets: 3, reps: "8-10", restSec: 75, animKey: "Archer Push-Up" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "40s", restSec: 40, animKey: "Plank" },
        ],
      },
      {
        title: "سینه + پشت بازو",
        focus: "ترکیبی فشاری",
        exercises: [
          { name: "پرس سینه دمبل (Dumbbell Bench Press)", muscle: "سینه", sets: 4, reps: "10-12", restSec: 75, animKey: "Dumbbell Bench Press" },
          { name: "شنا پرشی (Clap Push-Up)", muscle: "سینه و توان", sets: 3, reps: "6-10", restSec: 75, animKey: "Clap Push-Up" },
          { name: "پشت بازو سیم‌کش (Triceps Pushdown)", muscle: "پشت بازو", sets: 4, reps: "12-15", restSec: 60, animKey: "Triceps Pushdown" },
          { name: "دیپ پارالل (Dips)", muscle: "پشت بازو و سینه", sets: 3, reps: "8-12", restSec: 75, animKey: "Dips" },
        ],
      },
    ],
  },
  {
    slug: "m-power-30",
    gender: "men",
    title: "قدرت سه‌گانه ۳۰ روزه",
    tagline: "اسکوات، پرس، ددلیفت — قوی‌تر از همیشه",
    description:
      "برنامهٔ قدرت بر پایهٔ سه حرکت پاورلیفتینگ. بار تدریجی هفتگی و تکنیک تمیز — عدد وزنه‌هایت را در این ۳۰ روز به‌طور جدی بالا می‌بَری.",
    disciplineLabel: "پاورلیفتینگ",
    difficulty: "advanced",
    durationDays: 30,
    daysPerWeek: 4,
    minutesPerDay: 55,
    equipment: "باشگاه (رک + هالتر)",
    cover: "/images/challenges/men/m-power-30.jpg",
    accent: { from: "#7c2d12", via: "#9a3412", to: "#1c0a03" },
    emoji: "🏋️",
    dayTemplates: [
      {
        title: "روز اسکوات",
        focus: "پا و توان",
        exercises: [
          { name: "اسکوات هالتر (Barbell Back Squat)", muscle: "پا", sets: 5, reps: "5", restSec: 150, animKey: "Barbell Back Squat" },
          { name: "ددل‌لیفت رومانیایی (Romanian Deadlift)", muscle: "همسترینگ", sets: 4, reps: "8-10", restSec: 90, animKey: "Romanian Deadlift" },
          { name: "لانج (Lunge)", muscle: "پا و باسن", sets: 3, reps: "10-12", restSec: 75, animKey: "Lunge" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "45s", restSec: 40, animKey: "Plank" },
        ],
      },
      {
        title: "روز پرس سینه",
        focus: "قدرت فشاری",
        exercises: [
          { name: "پرس سینه هالتر (Barbell Bench Press)", muscle: "سینه", sets: 5, reps: "5", restSec: 150, animKey: "Barbell Bench Press" },
          { name: "پرس سرشانه هالتر (Barbell Shoulder Press)", muscle: "شانه", sets: 4, reps: "6-8", restSec: 90, animKey: "Barbell Shoulder Press" },
          { name: "دیپ پارالل (Dips)", muscle: "پشت بازو و سینه", sets: 3, reps: "8-12", restSec: 75, animKey: "Dips" },
          { name: "پشت بازو سیم‌کش (Triceps Pushdown)", muscle: "پشت بازو", sets: 3, reps: "12-15", restSec: 60, animKey: "Triceps Pushdown" },
        ],
      },
      {
        title: "روز ددلیفت",
        focus: "زنجیرهٔ پشتی",
        exercises: [
          { name: "ددل‌لیفت هالتر (Barbell Deadlift)", muscle: "پشت", sets: 5, reps: "4-5", restSec: 180, animKey: "Barbell Deadlift" },
          { name: "زیربغل هالتر خم (Bent-Over Barbell Row)", muscle: "زیربغل", sets: 4, reps: "8-10", restSec: 90, animKey: "Bent Over Barbell Row" },
          { name: "شراگ دمبل (Dumbbell Shrug)", muscle: "تراپezius", sets: 3, reps: "12-15", restSec: 60, animKey: "Dumbbell Shrug" },
          { name: "جلو بازو هالتر (Barbell Bicep Curl)", muscle: "جلو بازو", sets: 3, reps: "10-12", restSec: 60, animKey: "Barbell Bicep Curl" },
        ],
      },
      {
        title: "روز کمکی و پمپ",
        focus: "عضلات کمکی",
        exercises: [
          { name: "پرس سرشانه دمبل (Dumbbell Shoulder Press)", muscle: "شانه", sets: 4, reps: "8-10", restSec: 75, animKey: "Dumbbell Shoulder Press" },
          { name: "زیربغل سیم‌کش از جلو (Lat Pulldown)", muscle: "زیربغل", sets: 4, reps: "10-12", restSec: 75, animKey: "Lat Pulldown" },
          { name: "اسکوات گابلِت (Goblet Squat)", muscle: "پا", sets: 3, reps: "12-15", restSec: 60, animKey: "Goblet Squat" },
          { name: "فیس‌پول (Face Pull)", muscle: "پشت شانه", sets: 3, reps: "15-20", restSec: 60, animKey: "Face Pull" },
          { name: "پل باسن (Glute Bridge)", muscle: "باسن", sets: 3, reps: "15-20", restSec: 60, animKey: "Glute Bridge" },
        ],
      },
    ],
  },
  {
    slug: "m-crossfit-21",
    gender: "men",
    title: "کراس‌فیت انفجاری ۲۱ روزه",
    tagline: "۲۱ روز، قلبی که بترکد و بدنی که بسوزد",
    description:
      "سیرکویت‌های پرشدت با استراحت کوتاه — ترکیب قدرت، هوازی و توان انفجاری. هر جلسه یک چالش جدید؛ مناسب کسانی که از روتین خسته‌اند.",
    disciplineLabel: "کراس‌فیت",
    difficulty: "advanced",
    durationDays: 21,
    daysPerWeek: 5,
    minutesPerDay: 30,
    equipment: "بدون تجهیزات (اختیاری: کتل‌بل)",
    cover: "/images/challenges/men/m-crossfit-21.jpg",
    accent: { from: "#dc2626", via: "#ea580c", to: "#450a0a" },
    emoji: "⚡",
    dayTemplates: [
      {
        title: "سیرکویت انفجاری ۱",
        focus: "فول‌بادی",
        exercises: [
          { name: "برپی (Burpee)", muscle: "فول‌بادی", sets: 4, reps: "12", restSec: 45, animKey: "Burpee" },
          { name: "اسکوات پرشی (Jump Squat)", muscle: "پا", sets: 4, reps: "15", restSec: 45, animKey: "Jump Squat" },
          { name: "کوهنورد درجا (Mountain Climbers)", muscle: "شکم و هوازی", sets: 4, reps: "30s", restSec: 40, animKey: "Mountain Climbers" },
          { name: "شنا (Push-Up)", muscle: "سینه", sets: 4, reps: "12-15", restSec: 45, animKey: "Push-Up" },
        ],
      },
      {
        title: "سیرکویت انفجاری ۲",
        focus: "پا و قلب",
        exercises: [
          { name: "اسکیپ ردیف (Skater Jumps)", muscle: "پا و تعادل", sets: 4, reps: "16-20", restSec: 40, animKey: "Skater Jumps" },
          { name: "لانج پرشی (Plyo Lunge)", muscle: "پا", sets: 4, reps: "12-16", restSec: 45, animKey: "Plyo Lunge" },
          { name: "اسکات و پرش ستاره (Star Jump Squat)", muscle: "فول‌بادی", sets: 3, reps: "10-12", restSec: 60, animKey: "Star Jump Squat" },
          { name: "پلانک پا باز (Plank Jack)", muscle: "مرکز بدن", sets: 3, reps: "20-24", restSec: 40, animKey: "Plank Jack" },
        ],
      },
      {
        title: "سیرکویت انفجاری ۳",
        focus: "بالاتنه و هوازی",
        exercises: [
          { name: "شنا پرشی (Clap Push-Up)", muscle: "سینه و توان", sets: 3, reps: "8-10", restSec: 60, animKey: "Clap Push-Up" },
          { name: "جک پرش (Jumping Jacks)", muscle: "هوازی", sets: 4, reps: "40s", restSec: 30, animKey: "Jumping Jacks" },
          { name: "اسپرینت درجا (High Knees)", muscle: "هوازی", sets: 4, reps: "30s", restSec: 30, animKey: "High Knees" },
          { name: "شنا دست‌جمع (Diamond Push-Up)", muscle: "پشت بازو", sets: 3, reps: "12-15", restSec: 45, animKey: "Diamond Push-Up" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "45s", restSec: 40, animKey: "Plank" },
        ],
      },
    ],
  },
  {
    slug: "m-calisthenics-30",
    gender: "men",
    title: "کالیستنیکس ۳۰ روزه",
    tagline: "وزن بدنت، بهترین باشگاهِ دنیا",
    description:
      "قدرت واقعی با وزن بدن: شنا، بارفیکس، دیپ و پلانک‌های پیشرفته. ۳۰ روز برای بدنی قوی، کاربردی و خوش‌فرم — هر جا، بدون باشگاه.",
    disciplineLabel: "کالیستنیکس",
    difficulty: "intermediate",
    durationDays: 30,
    daysPerWeek: 4,
    minutesPerDay: 35,
    equipment: "میلهٔ بارفیکس + پارالل",
    cover: "/images/challenges/men/m-calisthenics-30.jpg",
    accent: { from: "#059669", via: "#047857", to: "#022c22" },
    emoji: "🤸",
    dayTemplates: [
      {
        title: "فشار (شنا و دیپ)",
        focus: "سینه، شانه، پشت بازو",
        exercises: [
          { name: "شنا (Push-Up)", muscle: "سینه", sets: 4, reps: "15-20", restSec: 60, animKey: "Push-Up" },
          { name: "دیپ پارالل (Dips)", muscle: "پشت بازو و سینه", sets: 4, reps: "8-12", restSec: 75, animKey: "Dips" },
          { name: "شنا دست‌جمع (Diamond Push-Up)", muscle: "پشت بازو", sets: 3, reps: "12-15", restSec: 60, animKey: "Diamond Push-Up" },
          { name: "شنا بالاسینه (Incline Push-Up)", muscle: "سینه بالا", sets: 3, reps: "12-18", restSec: 60, animKey: "Incline Push-Up" },
        ],
      },
      {
        title: "کشش (بارفیکس و رِو)",
        focus: "پشت و جلو بازو",
        exercises: [
          { name: "بارفیکس (Pull-Up)", muscle: "زیربغل", sets: 4, reps: "6-10", restSec: 90, animKey: "Pull-Up" },
          { name: "بارفیکس استرالیایی (Australian Pull-Up)", muscle: "زیربغل میانی", sets: 3, reps: "10-12", restSec: 75, animKey: "Inverted Row" },
          { name: "بارفیکس با کمک کش (Band-Assisted Pull-Up)", muscle: "زیربغل", sets: 3, reps: "8-10", restSec: 75, animKey: "Band Assisted Pull-Up" },
          { name: "شنا دست‌جمع (Diamond Push-Up)", muscle: "پشت بازو", sets: 3, reps: "12-15", restSec: 60, animKey: "Diamond Push-Up" },
        ],
      },
      {
        title: "مرکز بدن و پا",
        focus: "ثبات کالیستنیکس",
        exercises: [
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 4, reps: "50s", restSec: 45, animKey: "Plank" },
          { name: "پلانک جانبی (Side Plank)", muscle: "پهلو", sets: 3, reps: "30s", restSec: 45, animKey: "Side Plank" },
          { name: "بالازدن پاها در آویزان (Hanging Leg Raise)", muscle: "شکم پایین", sets: 3, reps: "8-12", restSec: 60, animKey: "Hanging Leg Raise" },
          { name: "اسکوات با وزن بدن (Bodyweight Squat)", muscle: "پا", sets: 4, reps: "20-25", restSec: 60, animKey: "Bodyweight Squat" },
          { name: "لانج (Lunge)", muscle: "پا", sets: 3, reps: "12-14", restSec: 60, animKey: "Lunge" },
        ],
      },
    ],
  },
  {
    slug: "m-pullup-30",
    gender: "men",
    title: "بارفیکس: از صفر تا ۱۰",
    tagline: "نمی‌توانی یک بار بزنی؟ ۳۰ روز بعد ۱۰ می‌زنی",
    description:
      "سیستم پیشرفت گام‌به‌گام فیتاپ برای بارفیکس: از آویزان‌شدن و رِو منفی تا بارفیکس کامل و نهایتاً ۱۰ تکرار پیوسته. دقیقاً همان چیزی که برای شروع از صفر لازم است.",
    disciplineLabel: "بارفیکس",
    difficulty: "beginner",
    durationDays: 30,
    daysPerWeek: 4,
    minutesPerDay: 25,
    equipment: "میلهٔ بارفیکس (اختیاری: کش کمکی)",
    cover: "/images/challenges/men/m-pullup-30.jpg",
    accent: { from: "#0d9488", via: "#0f766e", to: "#042f2e" },
    emoji: "🎯",
    dayTemplates: [
      {
        title: "کشش و آویزان‌شدن",
        focus: "بنیان قدرت کششی",
        exercises: [
          { name: "بارفیکس با کمک کش (Band-Assisted Pull-Up)", muscle: "زیربغل", sets: 4, reps: "6-8", restSec: 90, animKey: "Band Assisted Pull-Up" },
          { name: "بارفیکس استرالیایی (Australian Pull-Up)", muscle: "زیربغل میانی", sets: 3, reps: "10-12", restSec: 75, animKey: "Inverted Row" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "40s", restSec: 40, animKey: "Plank" },
          { name: "جلو بازو دمبل (Dumbbell Bicep Curl)", muscle: "جلو بازو", sets: 3, reps: "10-12", restSec: 60, animKey: "Dumbbell Bicep Curl" },
        ],
      },
      {
        title: "بارفیکس تکراری",
        focus: "تعداد و استقامت",
        exercises: [
          { name: "بارفیکس (Pull-Up)", muscle: "زیربغل", sets: 5, reps: "3-6", restSec: 120, animKey: "Pull-Up" },
          { name: "بارفیکس استرالیایی (Australian Pull-Up)", muscle: "زیربغل میانی", sets: 3, reps: "12-15", restSec: 75, animKey: "Inverted Row" },
          { name: "زیربغل سیم‌کش از جلو (Lat Pulldown)", muscle: "زیربغل", sets: 3, reps: "10-12", restSec: 75, animKey: "Lat Pulldown" },
          { name: "چکشی جلو بازو (Hammer Curl)", muscle: "بازو و ساعد", sets: 3, reps: "10-12", restSec: 60, animKey: "Hammer Curl" },
        ],
      },
      {
        title: "قدرت کششی کامل",
        focus: "پشت و بازو",
        exercises: [
          { name: "بارفیکس (Pull-Up)", muscle: "زیربغل", sets: 5, reps: "4-8", restSec: 120, animKey: "Pull-Up" },
          { name: "زیربغل دمبل تک‌دست (Single-Arm Dumbbell Row)", muscle: "زیربغل", sets: 3, reps: "10-12", restSec: 60, animKey: "Single Arm Dumbbell Row" },
          { name: "فیس‌پول (Face Pull)", muscle: "پشت شانه", sets: 3, reps: "15-20", restSec: 60, animKey: "Face Pull" },
          { name: "شنا (Push-Up)", muscle: "سینه", sets: 3, reps: "12-18", restSec: 60, animKey: "Push-Up" },
          { name: "پل باسن (Glute Bridge)", muscle: "باسن و کمر", sets: 3, reps: "15-20", restSec: 45, animKey: "Glute Bridge" },
        ],
      },
    ],
  },
  {
    slug: "m-hiit-21",
    gender: "men",
    title: "چربی‌سوزی HIIT ۲۱ روزه",
    tagline: "۲۱ روز HIIT — چربی بسوزان، عضله نگه‌دار",
    description:
      "بازه‌های شدت بالا با استراحت کوتاه؛ متابولیسم را تا ساعت‌ها بعد از تمرین بالا نگه می‌دارد. برای سوزاندن شکم و پهلو در کمترین زمان ممکن — فقط ۲۵ دقیقه در روز.",
    disciplineLabel: "HIIT و چربی‌سوزی",
    difficulty: "intermediate",
    durationDays: 21,
    daysPerWeek: 5,
    minutesPerDay: 25,
    equipment: "بدون تجهیزات",
    cover: "/images/challenges/men/m-hiit-21.jpg",
    accent: { from: "#e11d48", via: "#be123c", to: "#4c0519" },
    emoji: "🔥",
    dayTemplates: [
      {
        title: "HIIT فول‌بادی",
        focus: "چربی‌سوزی کل بدن",
        exercises: [
          { name: "برپی (Burpee)", muscle: "فول‌بادی", sets: 4, reps: "12", restSec: 40, animKey: "Burpee" },
          { name: "جک پرش (Jumping Jacks)", muscle: "هوازی", sets: 4, reps: "40s", restSec: 30, animKey: "Jumping Jacks" },
          { name: "اسکوات پرشی (Jump Squat)", muscle: "پا", sets: 4, reps: "15", restSec: 40, animKey: "Jump Squat" },
          { name: "کوهنورد درجا (Mountain Climbers)", muscle: "شکم و هوازی", sets: 4, reps: "30s", restSec: 40, animKey: "Mountain Climbers" },
        ],
      },
      {
        title: "HIIT پایین‌تنه",
        focus: "پا و چربی",
        exercises: [
          { name: "اسکیپ ردیف (Skater Jumps)", muscle: "پا و تعادل", sets: 4, reps: "16-20", restSec: 40, animKey: "Skater Jumps" },
          { name: "لانج پرشی (Plyo Lunge)", muscle: "پا", sets: 4, reps: "12-16", restSec: 45, animKey: "Plyo Lunge" },
          { name: "اسکوات سریع در جا (Fast Feet March)", muscle: "هوازی", sets: 4, reps: "40s", restSec: 30, animKey: "Fast Feet" },
          { name: "اسکات و پرش ستاره (Star Jump Squat)", muscle: "فول‌بادی", sets: 3, reps: "10-12", restSec: 60, animKey: "Star Jump Squat" },
        ],
      },
      {
        title: "HIIT بالاتنه + شکم",
        focus: "بالاتنه و مرکز بدن",
        exercises: [
          { name: "شنا (Push-Up)", muscle: "سینه", sets: 4, reps: "12-18", restSec: 40, animKey: "Push-Up" },
          { name: "اسپرینت درجا (High Knees)", muscle: "هوازی", sets: 4, reps: "30s", restSec: 30, animKey: "High Knees" },
          { name: "پلانک پا باز (Plank Jack)", muscle: "مرکز بدن", sets: 4, reps: "20-24", restSec: 40, animKey: "Plank Jack" },
          { name: "کرانچ دوچرخه (Bicycle Crunch)", muscle: "شکم", sets: 3, reps: "20-30", restSec: 40, animKey: "Bicycle Crunch" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "45s", restSec: 40, animKey: "Plank" },
        ],
      },
    ],
  },
  {
    slug: "m-functional-30",
    gender: "men",
    title: "فانکشنال ۳۰ روزه",
    tagline: "قدرتی که در زندگی واقعی به کار می‌آید",
    description:
      "حرکات چندمفصلی و کاربردی: بلند کردن، حمل کردن، چرخیدن و تعادل. بدنت را برای زندگی روزمره — نه فقط آینهٔ باشگاه — آماده می‌کند.",
    disciplineLabel: "فانکشنال",
    difficulty: "beginner",
    durationDays: 30,
    daysPerWeek: 4,
    minutesPerDay: 35,
    equipment: "دمبل/کتل‌بل (اختیاری)",
    cover: "/images/challenges/men/m-functional-30.jpg",
    accent: { from: "#ca8a04", via: "#a16207", to: "#422006" },
    emoji: "🧱",
    dayTemplates: [
      {
        title: "الگوهای پایه",
        focus: "اسکوات، لانج، حمل",
        exercises: [
          { name: "اسکوات با وزن بدن (Bodyweight Squat)", muscle: "پا", sets: 4, reps: "15-20", restSec: 60, animKey: "Bodyweight Squat" },
          { name: "لانج (Lunge)", muscle: "پا", sets: 3, reps: "12-14", restSec: 60, animKey: "Lunge" },
          { name: "قدم‌های بلند رو به جلو (Farmer March)", muscle: "تنه و گریپ", sets: 3, reps: "40s", restSec: 60, animKey: "Farmer March" },
          { name: "پل باسن (Glute Bridge)", muscle: "باسن", sets: 3, reps: "15-20", restSec: 45, animKey: "Glute Bridge" },
        ],
      },
      {
        title: "فشار و کشش کاربردی",
        focus: "بالاتنه کاربردی",
        exercises: [
          { name: "شنا (Push-Up)", muscle: "سینه", sets: 4, reps: "12-18", restSec: 60, animKey: "Push-Up" },
          { name: "بارفیکس استرالیایی (Australian Pull-Up)", muscle: "زیربغل", sets: 3, reps: "10-12", restSec: 75, animKey: "Inverted Row" },
          { name: "پرس سرشانه دمبل (Dumbbell Shoulder Press)", muscle: "شانه", sets: 3, reps: "10-12", restSec: 75, animKey: "Dumbbell Shoulder Press" },
          { name: "مرغ-سگ (Bird-Dog)", muscle: "ثبات تنه", sets: 3, reps: "10-12", restSec: 45, animKey: "Bird Dog" },
        ],
      },
      {
        title: "مرکز بدن و تعادل",
        focus: "ثبات و هماهنگی",
        exercises: [
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 4, reps: "45s", restSec: 45, animKey: "Plank" },
          { name: "ددباگ (Dead Bug)", muscle: "مرکز بدن", sets: 3, reps: "12-14", restSec: 45, animKey: "Dead Bug" },
          { name: "ترازوی تک‌پا (Single-Leg Balance)", muscle: "تعادل", sets: 3, reps: "30s", restSec: 40, animKey: "Single Leg Balance" },
          { name: "کوهنورد درجا (Mountain Climbers)", muscle: "شکم و هوازی", sets: 3, reps: "30s", restSec: 40, animKey: "Mountain Climbers" },
          { name: "کشش گربه-شتر (Cat-Cow Stretch)", muscle: "ستون فقرات", sets: 2, reps: "10", restSec: 30, animKey: "Cat Cow" },
        ],
      },
    ],
  },
  {
    slug: "m-trx-21",
    gender: "men",
    title: "TRX ۲۱ روزه",
    tagline: "دو بند، هزار تمرین — بدنی پایدار و قوی",
    description:
      "تمرین معلق با بندهای TRX: هر حرکت ناپایداری اضافه می‌کند و مرکز بدن را دوبرابر درگیر می‌کند. مناسب خانه و باشگاه؛ فقط یک نقطهٔ اتصال لازم داری.",
    disciplineLabel: "TRX",
    difficulty: "intermediate",
    durationDays: 21,
    daysPerWeek: 4,
    minutesPerDay: 30,
    equipment: "بند TRX",
    cover: "/images/challenges/men/m-trx-21.jpg",
    accent: { from: "#16a34a", via: "#15803d", to: "#052e16" },
    emoji: "🪢",
    dayTemplates: [
      {
        title: "TRX کششی",
        focus: "پشت و بازو",
        exercises: [
          { name: "روئینگ TRX ایستاده (TRX Row)", muscle: "زیربغل", sets: 4, reps: "10-12", restSec: 60, animKey: "TRX Row" },
          { name: "بارفیکس استرالیایی (Australian Pull-Up)", muscle: "زیربغل میانی", sets: 3, reps: "10-12", restSec: 75, animKey: "Inverted Row" },
          { name: "جلو بازو دمبل (Dumbbell Bicep Curl)", muscle: "جلو بازو", sets: 3, reps: "10-12", restSec: 60, animKey: "Dumbbell Bicep Curl" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "45s", restSec: 45, animKey: "Plank" },
        ],
      },
      {
        title: "TRX فشاری",
        focus: "سینه و شانه",
        exercises: [
          { name: "پرس سینه TRX (TRX Chest Press)", muscle: "سینه", sets: 4, reps: "10-12", restSec: 60, animKey: "TRX Chest Press" },
          { name: "شنا (Push-Up)", muscle: "سینه", sets: 3, reps: "12-18", restSec: 60, animKey: "Push-Up" },
          { name: "پرس سرشانه دمبل (Dumbbell Shoulder Press)", muscle: "شانه", sets: 3, reps: "10-12", restSec: 75, animKey: "Dumbbell Shoulder Press" },
          { name: "پلانک TRX (TRX Plank)", muscle: "مرکز بدن", sets: 3, reps: "40s", restSec: 45, animKey: "TRX Plank" },
        ],
      },
      {
        title: "TRX پا و مرکز بدن",
        focus: "پای معلق",
        exercises: [
          { name: "اسکوات TRX (TRX Squat)", muscle: "پا", sets: 4, reps: "12-15", restSec: 60, animKey: "TRX Squat" },
          { name: "لانج TRX (TRX Lunge)", muscle: "پا", sets: 3, reps: "10-12", restSec: 60, animKey: "TRX Lunge" },
          { name: "پل باسن (Glute Bridge)", muscle: "باسن", sets: 3, reps: "15-20", restSec: 45, animKey: "Glute Bridge" },
          { name: "پلانک لمس شانه (Shoulder-Tap Plank)", muscle: "مرکز بدن", sets: 3, reps: "16-20", restSec: 45, animKey: "Plank Shoulder Tap" },
          { name: "کشش کودک (Child's Pose)", muscle: "ریلکس", sets: 1, reps: "45s", restSec: 30, animKey: "Child Pose" },
        ],
      },
    ],
  },
  {
    slug: "m-pilates-21",
    gender: "men",
    title: "پیلاتس مردانه ۲۱ روزه",
    tagline: "مرکز بدنی فولادی — قدرت پنهان قهرمانان",
    description:
      "پیلاتس مخصوص آقایان: کنترل دقیق مرکز بدن، انعطاف و آگاهی حرکتی. ستون فقراتت را می‌فهمی، کمر تقویت می‌شود و قدرت واقعی از داخل بدن می‌جوشد.",
    disciplineLabel: "پیلاتس",
    difficulty: "beginner",
    durationDays: 21,
    daysPerWeek: 4,
    minutesPerDay: 25,
    equipment: "مت تمرین",
    cover: "/images/challenges/men/m-pilates-21.jpg",
    accent: { from: "#4f46e5", via: "#4338ca", to: "#1e1b4b" },
    emoji: "🧘",
    dayTemplates: [
      {
        title: "پیلاتس پایه",
        focus: "کنترل مرکز بدن",
        exercises: [
          { name: "صد پیلاتس (Pilates Hundred)", muscle: "شکم", sets: 2, reps: "60s", restSec: 45, animKey: "Pilates Hundred" },
          { name: "رول‌آپ پیلاتس (Pilates Roll-Up)", muscle: "شکم و ستون", sets: 3, reps: "8-10", restSec: 45, animKey: "Pilates Roll Up" },
          { name: "پل باسن پیلاتس (Pilates Shoulder Bridge)", muscle: "باسن و کمر", sets: 3, reps: "10-12", restSec: 45, animKey: "Pilates Bridge" },
          { name: "پیلاتس باز و بسته کردن پاها (Single-Leg Stretch)", muscle: "شکم", sets: 3, reps: "12-16", restSec: 40, animKey: "Single Leg Stretch" },
        ],
      },
      {
        title: "پیلاتس و ثبات",
        focus: "پایداری تنه",
        exercises: [
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "45s", restSec: 45, animKey: "Plank" },
          { name: "مرغ-سگ (Bird-Dog)", muscle: "ثبات تنه", sets: 3, reps: "10-12", restSec: 40, animKey: "Bird Dog" },
          { name: "ددباگ (Dead Bug)", muscle: "مرکز بدن", sets: 3, reps: "12-14", restSec: 40, animKey: "Dead Bug" },
          { name: "سوپرمن (Superman Hold)", muscle: "کمر", sets: 3, reps: "30s", restSec: 40, animKey: "Superman" },
        ],
      },
      {
        title: "پیلاتس پیشرفته",
        focus: "قدرت مرکزی",
        exercises: [
          { name: "صد پیلاتس (Pilates Hundred)", muscle: "شکم", sets: 2, reps: "90s", restSec: 45, animKey: "Pilates Hundred" },
          { name: "رول‌آپ پیلاتس (Pilates Roll-Up)", muscle: "شکم و ستون", sets: 3, reps: "10-12", restSec: 45, animKey: "Pilates Roll Up" },
          { name: "پلانک جانبی (Side Plank)", muscle: "پهلو", sets: 3, reps: "30s", restSec: 45, animKey: "Side Plank" },
          { name: "چرخش ستون فقرات نشسته (Seated Spinal Twist)", muscle: "انعطاف", sets: 2, reps: "10", restSec: 30, animKey: "Seated Twist" },
          { name: "کشش کودک (Child's Pose)", muscle: "ریلکس", sets: 1, reps: "45s", restSec: 30, animKey: "Child Pose" },
        ],
      },
    ],
  },
  {
    slug: "m-balance-14",
    gender: "men",
    title: "تعادل و ثبات ۱۴ روزه",
    tagline: "۱۴ روز تا بدنی که هیچ‌وقت زمین نمی‌خورد",
    description:
      "چالش کوتاه و طلایی برای ثبات: تعادل تک‌پا، ثبات مرکز بدن و کنترل عصبی-عضلانی. پیش‌نیاز پنهان همهٔ ورزش‌ها — و بهترین بیمهٔ زانو و مچ.",
    disciplineLabel: "تعادل",
    difficulty: "beginner",
    durationDays: 14,
    daysPerWeek: 4,
    minutesPerDay: 20,
    equipment: "بدون تجهیزات",
    cover: "/images/challenges/men/m-balance-14.jpg",
    accent: { from: "#0891b2", via: "#0e7490", to: "#083344" },
    emoji: "⚖️",
    dayTemplates: [
      {
        title: "تعادل پایه",
        focus: "ثبات ایستا",
        exercises: [
          { name: "ترازوی تک‌پا (Single-Leg Balance)", muscle: "تعادل", sets: 3, reps: "30s", restSec: 40, animKey: "Single Leg Balance" },
          { name: "مرغ-سگ (Bird-Dog)", muscle: "ثبات تنه", sets: 3, reps: "10-12", restSec: 40, animKey: "Bird Dog" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "40s", restSec: 40, animKey: "Plank" },
        ],
      },
      {
        title: "تعادل پویا",
        focus: "ثبات در حرکت",
        exercises: [
          { name: "اسکیپ ردیف (Skater Jumps)", muscle: "تعادل پویا", sets: 3, reps: "12-16", restSec: 45, animKey: "Skater Jumps" },
          { name: "لانج معکوس (Reverse Lunge)", muscle: "پا و تعادل", sets: 3, reps: "10-12", restSec: 60, animKey: "Reverse Lunge" },
          { name: "پلانک لمس شانه (Shoulder-Tap Plank)", muscle: "مرکز بدن", sets: 3, reps: "16-20", restSec: 45, animKey: "Plank Shoulder Tap" },
          { name: "ددباگ (Dead Bug)", muscle: "مرکز بدن", sets: 3, reps: "12-14", restSec: 40, animKey: "Dead Bug" },
        ],
      },
    ],
  },
  {
    slug: "m-fresh-start-14",
    gender: "men",
    title: "شروع دوباره ۱۴ روزه",
    tagline: "۲ هفته کوتاه تا برگشت به فرم — بدون باشگاه",
    description:
      "برای کسی که مدت‌هاست شروع نکرده: حرکات ساده و ایمن با وزن بدن در خانه. بدن آرام‌آرام به تمرین برمی‌گردد و عادت ورزش دوباره جا می‌افتد.",
    disciplineLabel: "شروع تمرین",
    difficulty: "beginner",
    durationDays: 14,
    daysPerWeek: 4,
    minutesPerDay: 20,
    equipment: "بدون تجهیزات — در خانه",
    cover: "/images/challenges/men/m-fresh-start-14.jpg",
    accent: { from: "#f59e0b", via: "#f97316", to: "#7c2d12" },
    emoji: "🌅",
    dayTemplates: [
      {
        title: "فعال‌سازی کل بدن",
        focus: "شروع ملایم",
        exercises: [
          { name: "اسکوات با وزن بدن (Bodyweight Squat)", muscle: "پا", sets: 3, reps: "12-15", restSec: 60, animKey: "Bodyweight Squat" },
          { name: "شنا زانو (Knee Push-Up)", muscle: "سینه", sets: 3, reps: "10-12", restSec: 60, animKey: "Knee Push-Up" },
          { name: "پل باسن (Glute Bridge)", muscle: "باسن", sets: 3, reps: "12-15", restSec: 45, animKey: "Glute Bridge" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 2, reps: "30s", restSec: 40, animKey: "Plank" },
        ],
      },
      {
        title: "قلب و ریه + مرکز بدن",
        focus: "هوازی سبک",
        exercises: [
          { name: "جک پرش (Jumping Jacks)", muscle: "هوازی", sets: 3, reps: "30s", restSec: 45, animKey: "Jumping Jacks" },
          { name: "اسکوات سریع در جا (Fast Feet March)", muscle: "هوازی", sets: 3, reps: "30s", restSec: 45, animKey: "Fast Feet" },
          { name: "ددباگ (Dead Bug)", muscle: "مرکز بدن", sets: 3, reps: "10-12", restSec: 45, animKey: "Dead Bug" },
          { name: "کشش گربه-شتر (Cat-Cow Stretch)", muscle: "ستون فقرات", sets: 2, reps: "10", restSec: 30, animKey: "Cat Cow" },
          { name: "کشش کودک (Child's Pose)", muscle: "ریلکس", sets: 1, reps: "45s", restSec: 30, animKey: "Child Pose" },
        ],
      },
    ],
  },
  {
    slug: "m-legs-30",
    gender: "men",
    title: "پای قدرتمند ۳۰ روزه",
    tagline: "روز پا را حذف نکن — پای قوی، بدن قوی",
    description:
      "اسکوات، لانج، ددلیفت رومانیایی و ساق: برنامهٔ کامل پایین‌تنه برای قدرت، پرش و فرم عضلانی پا. پای قوی یعنی متابولیسم بالاتر و بالاتنه‌ای قوی‌تر.",
    disciplineLabel: "پا",
    difficulty: "intermediate",
    durationDays: 30,
    daysPerWeek: 4,
    minutesPerDay: 40,
    equipment: "دمبل (یا وزن بدن در خانه)",
    cover: "/images/challenges/men/m-legs-30.jpg",
    accent: { from: "#b45309", via: "#92400e", to: "#451a03" },
    emoji: "🦵",
    dayTemplates: [
      {
        title: "قدرت پایه",
        focus: "اسکوات و هینج",
        exercises: [
          { name: "اسکوات گابلِت (Goblet Squat)", muscle: "پا", sets: 4, reps: "12-15", restSec: 75, animKey: "Goblet Squat" },
          { name: "پشت پا دمبل ایستاده (Dumbbell Romanian Deadlift)", muscle: "همسترینگ", sets: 4, reps: "10-12", restSec: 75, animKey: "Dumbbell RDL" },
          { name: "پل باسن تک‌پا (Single-Leg Glute Bridge)", muscle: "باسن", sets: 3, reps: "10-12", restSec: 60, animKey: "Single Leg Glute Bridge" },
          { name: "ساق پا ایستاده (Standing Calf Raise)", muscle: "ساق", sets: 4, reps: "15-20", restSec: 45, animKey: "Standing Calf Raise" },
        ],
      },
      {
        title: "پا و توان",
        focus: "تک‌پا و انفجار",
        exercises: [
          { name: "اسکوات بلغاری (Bulgarian Split Squat)", muscle: "پا", sets: 4, reps: "10-12", restSec: 75, animKey: "Bulgarian Split Squat" },
          { name: "لانج معکوس (Reverse Lunge)", muscle: "پا و باسن", sets: 3, reps: "12-14", restSec: 60, animKey: "Reverse Lunge" },
          { name: "اسکوات پرشی (Jump Squat)", muscle: "پا و توان", sets: 3, reps: "12-15", restSec: 60, animKey: "Jump Squat" },
          { name: "اسکوات جانبی (Side Lunge)", muscle: "داخل ران", sets: 3, reps: "10-12", restSec: 60, animKey: "Side Lunge" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "45s", restSec: 40, animKey: "Plank" },
        ],
      },
      {
        title: "پای کامل با وزن بدن",
        focus: "استقامت پا",
        exercises: [
          { name: "اسکوات با وزن بدن (Bodyweight Squat)", muscle: "پا", sets: 4, reps: "20-25", restSec: 60, animKey: "Bodyweight Squat" },
          { name: "لانج (Lunge)", muscle: "پا", sets: 3, reps: "14-16", restSec: 60, animKey: "Lunge" },
          { name: "کیک‌بک باسن (Glute Kickback)", muscle: "باسن", sets: 3, reps: "12-15", restSec: 45, animKey: "Glute Kickback" },
          { name: "اسکوات پرشی (Jump Squat)", muscle: "پا و توان", sets: 3, reps: "12-15", restSec: 60, animKey: "Jump Squat" },
          { name: "کشش کف پا و ساق (Calf Stretch)", muscle: "انعطاف", sets: 1, reps: "30s", restSec: 30, animKey: "Calf Stretch" },
        ],
      },
    ],
  },
];
