/**
 * v183 — چالش‌های خانم‌ها (۱۷ چالش) — الگوی محتوای ثابت جنسیتی
 * فقط کاربران خانم این ۱۷ چالش را می‌بینند (داشبورد + صفحهٔ چالش‌ها) — رایگان.
 * چالش‌های شاخص درخواست مالک: «باسن خوش‌فرم ۳۰ روزه» و «چربی‌سوزی ۲ ماهه».
 */
import type { ChallengeDef } from "./challenges-data";

export const CHALLENGES_WOMEN: ChallengeDef[] = [
  {
    slug: "w-glutes-30",
    gender: "women",
    title: "باسن خوش‌فرم ۳۰ روزه",
    tagline: "۳۰ روز، فرمی که همه چشم‌ها را می‌گیرد",
    description:
      "پرطرفدارترین چالش بانوان فیتاپ! ترکیب دقیق حرکات باسن (هیپ تراست، اسکوات، کیک‌بک) با پا و مرکز بدن — برای بالاتنهٔ خوش‌فرم، باسن گرد و پاهای کشیده.",
    disciplineLabel: "باسن و پا",
    difficulty: "beginner",
    durationDays: 30,
    daysPerWeek: 4,
    minutesPerDay: 30,
    equipment: "بدون تجهیزات (اختیاری: کش ورزشی)",
    cover: "/images/challenges/women/w-glutes-30.jpg",
    accent: { from: "#ec4899", via: "#db2777", to: "#500724" },
    emoji: "🍑",
    dayTemplates: [
      {
        title: "باسن و همسترینگ",
        focus: "شکل‌دهی باسن",
        exercises: [
          { name: "پل باسن (Glute Bridge)", muscle: "باسن", sets: 4, reps: "15-20", restSec: 45, animKey: "Glute Bridge" },
          { name: "کیک‌بک باسن (Glute Kickback)", muscle: "باسن", sets: 4, reps: "12-15", restSec: 45, animKey: "Glute Kickback" },
          { name: "پل باسن تک‌پا (Single-Leg Glute Bridge)", muscle: "باسن", sets: 3, reps: "10-12", restSec: 45, animKey: "Single Leg Glute Bridge" },
          { name: "پروانه باسن (Clamshell)", muscle: "باسن میانی", sets: 3, reps: "15-20", restSec: 40, animKey: "Clamshell" },
          { name: "پل جانبی لگن (Side-Lying Hip Abduction)", muscle: "باسن میانی", sets: 3, reps: "15-20", restSec: 40, animKey: "Side Hip Abduction" },
        ],
      },
      {
        title: "پا و باسن (اسکوات و لانج)",
        focus: "پای خوش‌فرم",
        exercises: [
          { name: "اسکوات با وزن بدن (Bodyweight Squat)", muscle: "پا و باسن", sets: 4, reps: "15-20", restSec: 60, animKey: "Bodyweight Squat" },
          { name: "لانج معکوس (Reverse Lunge)", muscle: "پا و باسن", sets: 3, reps: "12-14", restSec: 60, animKey: "Reverse Lunge" },
          { name: "اسکوات جانبی (Side Lunge)", muscle: "داخل ران", sets: 3, reps: "10-12", restSec: 60, animKey: "Side Lunge" },
          { name: "اسکوات بلغاری (Bulgarian Split Squat)", muscle: "پا و باسن", sets: 3, reps: "10-12", restSec: 60, animKey: "Bulgarian Split Squat" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "30s", restSec: 40, animKey: "Plank" },
        ],
      },
      {
        title: "باسن + مرکز بدن",
        focus: "فرم کلی",
        exercises: [
          { name: "هیپ تراست (Hip Thrust)", muscle: "باسن", sets: 4, reps: "15-20", restSec: 60, animKey: "Hip Thrust" },
          { name: "کیک‌بک باسن (Glute Kickback)", muscle: "باسن", sets: 3, reps: "12-15", restSec: 45, animKey: "Glute Kickback" },
          { name: "ددباگ (Dead Bug)", muscle: "مرکز بدن", sets: 3, reps: "12-14", restSec: 40, animKey: "Dead Bug" },
          { name: "پل باسن (Glute Bridge)", muscle: "باسن", sets: 3, reps: "15-20", restSec: 45, animKey: "Glute Bridge" },
          { name: "کشش گربه-شتر (Cat-Cow Stretch)", muscle: "ستون فقرات", sets: 2, reps: "10", restSec: 30, animKey: "Cat Cow" },
        ],
      },
    ],
  },
  {
    slug: "w-fatburn-60",
    gender: "women",
    title: "چربی‌سوزی ۲ ماهه",
    tagline: "۶۰ روز مسیر تبدیل شدن — بدون رژیم سخت",
    description:
      "چالش کامل ۲ ماههٔ فیتاپ: ترکیب تمرین قدرتی، هوازی و HIIT که چربی را می‌سوزاند و فرم بدن را می‌سازد. همراه با توصیه‌های سبک تغذیه در هر روز — نتیجه‌ای که دیده می‌شود.",
    disciplineLabel: "چربی‌سوزی",
    difficulty: "beginner",
    durationDays: 60,
    daysPerWeek: 5,
    minutesPerDay: 30,
    equipment: "بدون تجهیزات — در خانه",
    cover: "/images/challenges/women/w-fatburn-60.jpg",
    accent: { from: "#f43f5e", via: "#e11d48", to: "#4c0519" },
    emoji: "🔥",
    dayTemplates: [
      {
        title: "چربی‌سوز فول‌بادی",
        focus: "هوازی و قدرتی",
        exercises: [
          { name: "جک پرش (Jumping Jacks)", muscle: "هوازی", sets: 3, reps: "40s", restSec: 30, animKey: "Jumping Jacks" },
          { name: "اسکوات با وزن بدن (Bodyweight Squat)", muscle: "پا", sets: 3, reps: "15-18", restSec: 45, animKey: "Bodyweight Squat" },
          { name: "شنا زانو (Knee Push-Up)", muscle: "سینه و بازو", sets: 3, reps: "10-12", restSec: 45, animKey: "Knee Push-Up" },
          { name: "کوهنورد درجا (Mountain Climbers)", muscle: "شکم و هوازی", sets: 3, reps: "30s", restSec: 40, animKey: "Mountain Climbers" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "30s", restSec: 40, animKey: "Plank" },
        ],
      },
      {
        title: "پای خوش‌فرم و باسن",
        focus: "پایین‌تنه",
        exercises: [
          { name: "اسکوات با وزن بدن (Bodyweight Squat)", muscle: "پا و باسن", sets: 4, reps: "15-20", restSec: 45, animKey: "Bodyweight Squat" },
          { name: "لانج معکوس (Reverse Lunge)", muscle: "پا و باسن", sets: 3, reps: "12-14", restSec: 60, animKey: "Reverse Lunge" },
          { name: "پل باسن (Glute Bridge)", muscle: "باسن", sets: 3, reps: "15-20", restSec: 45, animKey: "Glute Bridge" },
          { name: "اسکوات پرشی (Jump Squat)", muscle: "پا و هوازی", sets: 3, reps: "10-12", restSec: 60, animKey: "Jump Squat" },
          { name: "ساق پا ایستاده (Standing Calf Raise)", muscle: "ساق", sets: 3, reps: "15-20", restSec: 40, animKey: "Standing Calf Raise" },
        ],
      },
      {
        title: "شکم و کمر",
        focus: "مرکز بدن",
        exercises: [
          { name: "کرانچ شکم (Crunch)", muscle: "شکم", sets: 3, reps: "15-18", restSec: 40, animKey: "Crunch" },
          { name: "کرانچ دوچرخه (Bicycle Crunch)", muscle: "شکم و پهلو", sets: 3, reps: "16-24", restSec: 40, animKey: "Bicycle Crunch" },
          { name: "پل باسن (Glute Bridge)", muscle: "باسن و کمر", sets: 3, reps: "15-20", restSec: 45, animKey: "Glute Bridge" },
          { name: "سوپرمن (Superman Hold)", muscle: "کمر", sets: 3, reps: "25s", restSec: 40, animKey: "Superman" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "35s", restSec: 40, animKey: "Plank" },
        ],
      },
      {
        title: "HIIT سبک بانوان",
        focus: "چربی‌سوزی شدید",
        exercises: [
          { name: "برپی (Burpee)", muscle: "فول‌بادی", sets: 3, reps: "8-10", restSec: 45, animKey: "Burpee" },
          { name: "اسکیپ ردیف (Skater Jumps)", muscle: "پا و تعادل", sets: 3, reps: "12-16", restSec: 40, animKey: "Skater Jumps" },
          { name: "اسپرینت درجا (High Knees)", muscle: "هوازی", sets: 3, reps: "25s", restSec: 35, animKey: "High Knees" },
          { name: "لانج پرشی (Plyo Lunge)", muscle: "پا", sets: 3, reps: "10-12", restSec: 45, animKey: "Plyo Lunge" },
          { name: "کشش کودک (Child's Pose)", muscle: "ریلکس", sets: 1, reps: "45s", restSec: 30, animKey: "Child Pose" },
        ],
      },
    ],
  },
  {
    slug: "w-core-21",
    gender: "women",
    title: "شکم و کمر ۲۱ روزه",
    tagline: "۲۱ روز تا میان‌تنه‌ای سفت و کبریتی",
    description:
      "چالش تخصصی مرکز بدن برای بانوان: شکم، پهلو و عضلات کمر — بدون فشار به گردن و با تکنیک ایمن پیلاتسی. میان‌تنه قوی = قامت بهتر و شکم صاف‌تر.",
    disciplineLabel: "شکم و مرکز بدن",
    difficulty: "beginner",
    durationDays: 21,
    daysPerWeek: 4,
    minutesPerDay: 25,
    equipment: "مت تمرین",
    cover: "/images/challenges/women/w-core-21.jpg",
    accent: { from: "#8b5cf6", via: "#7c3aed", to: "#2e1065" },
    emoji: "✨",
    dayTemplates: [
      {
        title: "شکم کامل",
        focus: "بالا و پایین شکم",
        exercises: [
          { name: "کرانچ شکم (Crunch)", muscle: "شکم", sets: 3, reps: "15-20", restSec: 40, animKey: "Crunch" },
          { name: "بالازدن پا در حالت خوابیده (Leg Raise)", muscle: "شکم پایین", sets: 3, reps: "10-14", restSec: 40, animKey: "Lying Leg Raise" },
          { name: "کرانچ متقاطع (Cross-Body Crunch)", muscle: "شکم و پهلو", sets: 3, reps: "14-18", restSec: 40, animKey: "Cross-Body Crunch" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "30s", restSec: 40, animKey: "Plank" },
        ],
      },
      {
        title: "پهلو و کمر",
        focus: "فرم پهلو و تقویت کمر",
        exercises: [
          { name: "پلانک جانبی (Side Plank)", muscle: "پهلو", sets: 3, reps: "20-30s", restSec: 45, animKey: "Side Plank" },
          { name: "روسی پیچ (Russian Twist)", muscle: "پهلو", sets: 3, reps: "16-20", restSec: 40, animKey: "Russian Twist" },
          { name: "سوپرمن (Superman Hold)", muscle: "کمر", sets: 3, reps: "25s", restSec: 40, animKey: "Superman" },
          { name: "مرغ-سگ (Bird-Dog)", muscle: "ثبات تنه", sets: 3, reps: "10-12", restSec: 40, animKey: "Bird Dog" },
        ],
      },
      {
        title: "پیلاتس مرکز بدن",
        focus: "کنترل و کشیدگی",
        exercises: [
          { name: "صد پیلاتس (Pilates Hundred)", muscle: "شکم", sets: 2, reps: "60s", restSec: 45, animKey: "Pilates Hundred" },
          { name: "رول‌آپ پیلاتس (Pilates Roll-Up)", muscle: "شکم و ستون", sets: 3, reps: "8-10", restSec: 45, animKey: "Pilates Roll Up" },
          { name: "پیلاتس باز و بسته کردن پاها (Single-Leg Stretch)", muscle: "شکم", sets: 3, reps: "12-16", restSec: 40, animKey: "Single Leg Stretch" },
          { name: "ددباگ (Dead Bug)", muscle: "مرکز بدن", sets: 3, reps: "12-14", restSec: 40, animKey: "Dead Bug" },
          { name: "کشش کودک (Child's Pose)", muscle: "ریلکس", sets: 1, reps: "45s", restSec: 30, animKey: "Child Pose" },
        ],
      },
    ],
  },
  {
    slug: "w-legs-30",
    gender: "women",
    title: "پا و ران خوش‌فرم ۳۰ روزه",
    tagline: "ران‌های کشیده و پاهایی زیبا — ۳۰ روز",
    description:
      "فرم‌دهی تخصصی پا: داخل و پشت ران، چهارسر و ساق. ترکیب حرکات کشیده‌کننده و شکل‌دهنده تا پاهاfirm و خوش‌فرم شوند — نه فقط لاغر.",
    disciplineLabel: "پا و ران",
    difficulty: "beginner",
    durationDays: 30,
    daysPerWeek: 4,
    minutesPerDay: 30,
    equipment: "بدون تجهیزات (اختیاری: کش)",
    cover: "/images/challenges/women/w-legs-30.jpg",
    accent: { from: "#d946ef", via: "#c026d3", to: "#4a044e" },
    emoji: "🦵",
    dayTemplates: [
      {
        title: "اسکوات و لانج",
        focus: "کل پا",
        exercises: [
          { name: "اسکوات با وزن بدن (Bodyweight Squat)", muscle: "پا", sets: 4, reps: "15-20", restSec: 60, animKey: "Bodyweight Squat" },
          { name: "لانج معکوس (Reverse Lunge)", muscle: "پا و باسن", sets: 3, reps: "12-14", restSec: 60, animKey: "Reverse Lunge" },
          { name: "اسکوات جانبی (Side Lunge)", muscle: "داخل ران", sets: 3, reps: "10-12", restSec: 60, animKey: "Side Lunge" },
          { name: "پل باسن (Glute Bridge)", muscle: "باسن", sets: 3, reps: "15-20", restSec: 45, animKey: "Glute Bridge" },
        ],
      },
      {
        title: "داخل و پشت ران",
        focus: "فرم ران",
        exercises: [
          { name: "پل جانبی لگن (Side-Lying Hip Abduction)", muscle: "باسن میانی", sets: 3, reps: "15-20", restSec: 40, animKey: "Side Hip Abduction" },
          { name: "پروانه باسن (Clamshell)", muscle: "باسن میانی", sets: 3, reps: "15-20", restSec: 40, animKey: "Clamshell" },
          { name: "کیک‌بک باسن (Glute Kickback)", muscle: "باسن و پشت پا", sets: 3, reps: "12-15", restSec: 45, animKey: "Glute Kickback" },
          { name: "اسکوات بلغاری (Bulgarian Split Squat)", muscle: "پا", sets: 3, reps: "10-12", restSec: 60, animKey: "Bulgarian Split Squat" },
        ],
      },
      {
        title: "پا و هوازی سبک",
        focus: "فرم + چربی",
        exercises: [
          { name: "اسکوات پرشی (Jump Squat)", muscle: "پا و هوازی", sets: 3, reps: "10-12", restSec: 60, animKey: "Jump Squat" },
          { name: "اسکیپ ردیف (Skater Jumps)", muscle: "پا و تعادل", sets: 3, reps: "12-16", restSec: 45, animKey: "Skater Jumps" },
          { name: "ساق پا ایستاده (Standing Calf Raise)", muscle: "ساق", sets: 4, reps: "15-20", restSec: 40, animKey: "Standing Calf Raise" },
          { name: "اسکوات با وزن بدن (Bodyweight Squat)", muscle: "پا", sets: 3, reps: "15-18", restSec: 60, animKey: "Bodyweight Squat" },
          { name: "کشش کف پا و ساق (Calf Stretch)", muscle: "انعطاف", sets: 1, reps: "30s", restSec: 30, animKey: "Calf Stretch" },
        ],
      },
    ],
  },
  {
    slug: "w-toning-30",
    gender: "women",
    title: "فرم‌دهی تمام‌بدن ۳۰ روزه",
    tagline: "نه لاغر صرف، نه عضلانی صرف — فرم ایده‌آل",
    description:
      "ترکیب متوازن قدرت و هوازی برای فرم کلی بدن: بازو، پشت، پا، باسن و شکم. همان چیزی که بیشتر بانوان دنبالش هستند — بدنی خوش‌فرم و تناسب‌اندام واقعی.",
    disciplineLabel: "فرم‌دهی",
    difficulty: "beginner",
    durationDays: 30,
    daysPerWeek: 4,
    minutesPerDay: 35,
    equipment: "دمبل سبک (اختیاری)",
    cover: "/images/challenges/women/w-toning-30.jpg",
    accent: { from: "#06b6d4", via: "#0891b2", to: "#164e63" },
    emoji: "🌸",
    dayTemplates: [
      {
        title: "بالاتنه فرم‌دهی",
        focus: "بازو، پشت، شانه",
        exercises: [
          { name: "شنا زانو (Knee Push-Up)", muscle: "سینه و بازو", sets: 3, reps: "10-12", restSec: 45, animKey: "Knee Push-Up" },
          { name: "بارفیکس استرالیایی (Australian Pull-Up)", muscle: "پشت", sets: 3, reps: "8-12", restSec: 60, animKey: "Inverted Row" },
          { name: "پرس سرشانه دمبل (Dumbbell Shoulder Press)", muscle: "شانه", sets: 3, reps: "10-12", restSec: 60, animKey: "Dumbbell Shoulder Press" },
          { name: "اسپرانا (Reverse Fly)", muscle: "پشت شانه", sets: 3, reps: "12-15", restSec: 45, animKey: "Reverse Fly" },
        ],
      },
      {
        title: "پایین‌تنه فرم‌دهی",
        focus: "پا و باسن",
        exercises: [
          { name: "اسکوات با وزن بدن (Bodyweight Squat)", muscle: "پا و باسن", sets: 4, reps: "15-20", restSec: 60, animKey: "Bodyweight Squat" },
          { name: "لانج (Lunge)", muscle: "پا", sets: 3, reps: "12-14", restSec: 60, animKey: "Lunge" },
          { name: "پل باسن (Glute Bridge)", muscle: "باسن", sets: 3, reps: "15-20", restSec: 45, animKey: "Glute Bridge" },
          { name: "کیک‌بک باسن (Glute Kickback)", muscle: "باسن", sets: 3, reps: "12-15", restSec: 45, animKey: "Glute Kickback" },
        ],
      },
      {
        title: "فول‌بادی + هوازی",
        focus: "کل بدن",
        exercises: [
          { name: "جک پرش (Jumping Jacks)", muscle: "هوازی", sets: 3, reps: "35s", restSec: 35, animKey: "Jumping Jacks" },
          { name: "شنا زانو (Knee Push-Up)", muscle: "سینه و بازو", sets: 3, reps: "10-12", restSec: 45, animKey: "Knee Push-Up" },
          { name: "اسکوات با وزن بدن (Bodyweight Squat)", muscle: "پا", sets: 3, reps: "15-18", restSec: 45, animKey: "Bodyweight Squat" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "35s", restSec: 40, animKey: "Plank" },
          { name: "کشش کودک (Child's Pose)", muscle: "ریلکس", sets: 1, reps: "45s", restSec: 30, animKey: "Child Pose" },
        ],
      },
    ],
  },
  {
    slug: "w-physique-45",
    gender: "women",
    title: "فیزیک بانوان ۴۵ روزه",
    tagline: "قدرت واقعی، فرم رقابتی — ۴۵ روز",
    description:
      "برنامهٔ پیشرفتهٔ بانوان با الهام از فیزیک‌سازهای حرفه‌ای: تمرین قدرتی کامل بالاتنه و پایین‌تنه با بار تدریجی. برای خانم‌هایی که قوی‌تر بودن را می‌خواهند.",
    disciplineLabel: "فیزیک بانوان",
    difficulty: "advanced",
    durationDays: 45,
    daysPerWeek: 5,
    minutesPerDay: 50,
    equipment: "باشگاه (دمبل/دستگاه)",
    cover: "/images/challenges/women/w-physique-45.jpg",
    accent: { from: "#7c3aed", via: "#6d28d9", to: "#2e1065" },
    emoji: "👑",
    dayTemplates: [
      {
        title: "بالاتنه قدرتی",
        focus: "سینه، پشت، شانه",
        exercises: [
          { name: "پرس سینه دمبل (Dumbbell Bench Press)", muscle: "سینه", sets: 4, reps: "10-12", restSec: 75, animKey: "Dumbbell Bench Press" },
          { name: "زیربغل سیم‌کش از جلو (Lat Pulldown)", muscle: "زیربغل", sets: 4, reps: "10-12", restSec: 75, animKey: "Lat Pulldown" },
          { name: "پرس سرشانه دمبل (Dumbbell Shoulder Press)", muscle: "شانه", sets: 4, reps: "10-12", restSec: 75, animKey: "Dumbbell Shoulder Press" },
          { name: "زیربغل دمبل تک‌دست (Single-Arm Dumbbell Row)", muscle: "زیربغل", sets: 3, reps: "10-12", restSec: 60, animKey: "Single Arm Dumbbell Row" },
          { name: "اسپرانا (Reverse Fly)", muscle: "پشت شانه", sets: 3, reps: "15-18", restSec: 60, animKey: "Reverse Fly" },
        ],
      },
      {
        title: "پایین‌تنه قدرتی",
        focus: "پا و باسن",
        exercises: [
          { name: "اسکوات گابلِت (Goblet Squat)", muscle: "پا", sets: 4, reps: "12-15", restSec: 75, animKey: "Goblet Squat" },
          { name: "ددل‌لیفت رومانیایی (Romanian Deadlift)", muscle: "همسترینگ", sets: 4, reps: "10-12", restSec: 90, animKey: "Romanian Deadlift" },
          { name: "اسکوات بلغاری (Bulgarian Split Squat)", muscle: "پا و باسن", sets: 3, reps: "10-12", restSec: 75, animKey: "Bulgarian Split Squat" },
          { name: "هیپ تراست (Hip Thrust)", muscle: "باسن", sets: 4, reps: "15-20", restSec: 75, animKey: "Hip Thrust" },
          { name: "ساق پا ایستاده (Standing Calf Raise)", muscle: "ساق", sets: 3, reps: "15-20", restSec: 45, animKey: "Standing Calf Raise" },
        ],
      },
      {
        title: "بازو و مرکز بدن",
        focus: "جزئیات",
        exercises: [
          { name: "جلو بازو دمبل (Dumbbell Bicep Curl)", muscle: "جلو بازو", sets: 3, reps: "12-15", restSec: 60, animKey: "Dumbbell Bicep Curl" },
          { name: "پشت بازو سیم‌کش (Triceps Pushdown)", muscle: "پشت بازو", sets: 3, reps: "12-15", restSec: 60, animKey: "Triceps Pushdown" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 4, reps: "45s", restSec: 45, animKey: "Plank" },
          { name: "پلانک جانبی (Side Plank)", muscle: "پهلو", sets: 3, reps: "30s", restSec: 45, animKey: "Side Plank" },
          { name: "کرانچ دوچرخه (Bicycle Crunch)", muscle: "شکم", sets: 3, reps: "20-24", restSec: 45, animKey: "Bicycle Crunch" },
        ],
      },
    ],
  },
  {
    slug: "w-bikini-30",
    gender: "women",
    title: "بیکینی فیتنس ۳۰ روزه",
    tagline: "فرم ساحلی — آماده برای بهترین نسخهٔ خودت",
    description:
      "فرم‌دهی تابستانی: باسن، پا، شکم و شانه با حجم متوسط و استراحت کوتاه برای فرمی سفت و تابستانی. همان حس آماده‌شدن برای رقابت بیکینی فیتنس — در خانه.",
    disciplineLabel: "بیکینی فیتنس",
    difficulty: "intermediate",
    durationDays: 30,
    daysPerWeek: 5,
    minutesPerDay: 35,
    equipment: "کش ورزشی + دمبل سبک",
    cover: "/images/challenges/women/w-bikini-30.jpg",
    accent: { from: "#f59e0b", via: "#ec4899", to: "#831843" },
    emoji: "🌺",
    dayTemplates: [
      {
        title: "باسن و پا ساحلی",
        focus: "پایین‌تنه",
        exercises: [
          { name: "هیپ تراست (Hip Thrust)", muscle: "باسن", sets: 4, reps: "15-20", restSec: 60, animKey: "Hip Thrust" },
          { name: "اسکوات با وزن بدن (Bodyweight Squat)", muscle: "پا", sets: 4, reps: "18-22", restSec: 45, animKey: "Bodyweight Squat" },
          { name: "کیک‌بک باسن (Glute Kickback)", muscle: "باسن", sets: 3, reps: "12-15", restSec: 45, animKey: "Glute Kickback" },
          { name: "پل جانبی لگن (Side-Lying Hip Abduction)", muscle: "باسن میانی", sets: 3, reps: "15-20", restSec: 40, animKey: "Side Hip Abduction" },
          { name: "پل باسن (Glute Bridge)", muscle: "باسن", sets: 3, reps: "15-20", restSec: 45, animKey: "Glute Bridge" },
        ],
      },
      {
        title: "شکم و بالاتنه",
        focus: "مرکز بدن و فرم",
        exercises: [
          { name: "کرانچ شکم (Crunch)", muscle: "شکم", sets: 3, reps: "15-20", restSec: 40, animKey: "Crunch" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "40s", restSec: 40, animKey: "Plank" },
          { name: "شنا زانو (Knee Push-Up)", muscle: "سینه و بازو", sets: 3, reps: "10-14", restSec: 45, animKey: "Knee Push-Up" },
          { name: "نشر جانب دمبل (Dumbbell Lateral Raise)", muscle: "شانه", sets: 3, reps: "12-15", restSec: 45, animKey: "Dumbbell Lateral Raise" },
          { name: "روسی پیچ (Russian Twist)", muscle: "پهلو", sets: 3, reps: "20", restSec: 40, animKey: "Russian Twist" },
        ],
      },
      {
        title: "پمپاژ کامل",
        focus: "فول‌بادی سبک",
        exercises: [
          { name: "اسکوات پرشی (Jump Squat)", muscle: "پا", sets: 3, reps: "12-15", restSec: 60, animKey: "Jump Squat" },
          { name: "لانج معکوس (Reverse Lunge)", muscle: "پا و باسن", sets: 3, reps: "12-14", restSec: 60, animKey: "Reverse Lunge" },
          { name: "شنا زانو (Knee Push-Up)", muscle: "سینه و بازو", sets: 3, reps: "10-12", restSec: 45, animKey: "Knee Push-Up" },
          { name: "پل باسن تک‌پا (Single-Leg Glute Bridge)", muscle: "باسن", sets: 3, reps: "10-12", restSec: 45, animKey: "Single Leg Glute Bridge" },
          { name: "پلانک جانبی (Side Plank)", muscle: "پهلو", sets: 3, reps: "25s", restSec: 40, animKey: "Side Plank" },
        ],
      },
    ],
  },
  {
    slug: "w-power-30",
    gender: "women",
    title: "قدرتی بانوان ۳۰ روزه",
    tagline: "قوی بودن، جدیدترین جذابیت است",
    description:
      "چالش قدرت برای بانوان: اسکوات، ددلیفت و پرس با بار تدریجی. عضله‌سازی واقعی برای بدنی که هم قوی است و هم خوش‌فرم — ترس از «عضلانی شدن» را فراموش کن!",
    disciplineLabel: "پاورلیفتینگ",
    difficulty: "intermediate",
    durationDays: 30,
    daysPerWeek: 4,
    minutesPerDay: 50,
    equipment: "باشگاه (هالتر/دمبل)",
    cover: "/images/challenges/women/w-power-30.jpg",
    accent: { from: "#dc2626", via: "#991b1b", to: "#450a0a" },
    emoji: "🏋️‍♀️",
    dayTemplates: [
      {
        title: "روز پایین‌تنه قدرتی",
        focus: "اسکوات و هینج",
        exercises: [
          { name: "اسکوات گابلِت (Goblet Squat)", muscle: "پا", sets: 4, reps: "10-12", restSec: 90, animKey: "Goblet Squat" },
          { name: "ددل‌لیفت رومانیایی (Romanian Deadlift)", muscle: "همسترینگ", sets: 4, reps: "10-12", restSec: 90, animKey: "Romanian Deadlift" },
          { name: "لانج (Lunge)", muscle: "پا و باسن", sets: 3, reps: "12-14", restSec: 75, animKey: "Lunge" },
          { name: "پل باسن (Glute Bridge)", muscle: "باسن", sets: 3, reps: "15-20", restSec: 60, animKey: "Glute Bridge" },
        ],
      },
      {
        title: "روز بالاتنه قدرتی",
        focus: "فشار و کشش",
        exercises: [
          { name: "پرس سینه دمبل (Dumbbell Bench Press)", muscle: "سینه", sets: 4, reps: "10-12", restSec: 75, animKey: "Dumbbell Bench Press" },
          { name: "زیربغل سیم‌کش از جلو (Lat Pulldown)", muscle: "زیربغل", sets: 4, reps: "10-12", restSec: 75, animKey: "Lat Pulldown" },
          { name: "پرس سرشانه دمبل (Dumbbell Shoulder Press)", muscle: "شانه", sets: 4, reps: "10-12", restSec: 75, animKey: "Dumbbell Shoulder Press" },
          { name: "جلو بازو دمبل (Dumbbell Bicep Curl)", muscle: "جلو بازو", sets: 3, reps: "12-15", restSec: 60, animKey: "Dumbbell Bicep Curl" },
        ],
      },
      {
        title: "قدرت و مرکز بدن",
        focus: "کل بدن",
        exercises: [
          { name: "ددل‌لیفت هالتر (Barbell Deadlift)", muscle: "پشت", sets: 4, reps: "6-8", restSec: 120, animKey: "Barbell Deadlift" },
          { name: "اسکوات بلغاری (Bulgarian Split Squat)", muscle: "پا", sets: 3, reps: "10-12", restSec: 75, animKey: "Bulgarian Split Squat" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "45s", restSec: 45, animKey: "Plank" },
          { name: "پل باسن تک‌پا (Single-Leg Glute Bridge)", muscle: "باسن", sets: 3, reps: "10-12", restSec: 60, animKey: "Single Leg Glute Bridge" },
        ],
      },
    ],
  },
  {
    slug: "w-crossfit-21",
    gender: "women",
    title: "کراس‌فیت بانوان ۲۱ روزه",
    tagline: "۲۱ روز انرژی بی‌نهایت",
    description:
      "سیرکویت‌های پرشتاب بانوان: ترکیب قدرت و هوازی با ریتم تند. برای خانم‌هایی که از تمرین‌های یکنواخت خسته شده‌اند و می‌خواهند هر جلسه یک چالش تازه باشد.",
    disciplineLabel: "کراس‌فیت",
    difficulty: "intermediate",
    durationDays: 21,
    daysPerWeek: 5,
    minutesPerDay: 30,
    equipment: "بدون تجهیزات",
    cover: "/images/challenges/women/w-crossfit-21.jpg",
    accent: { from: "#ea580c", via: "#c2410c", to: "#431407" },
    emoji: "⚡",
    dayTemplates: [
      {
        title: "سیرکویت ۱",
        focus: "فول‌بادی",
        exercises: [
          { name: "برپی (Burpee)", muscle: "فول‌بادی", sets: 3, reps: "10", restSec: 45, animKey: "Burpee" },
          { name: "اسکوات پرشی (Jump Squat)", muscle: "پا", sets: 3, reps: "15", restSec: 45, animKey: "Jump Squat" },
          { name: "کوهنورد درجا (Mountain Climbers)", muscle: "شکم و هوازی", sets: 3, reps: "30s", restSec: 40, animKey: "Mountain Climbers" },
          { name: "شنا زانو (Knee Push-Up)", muscle: "سینه و بازو", sets: 3, reps: "10-12", restSec: 40, animKey: "Knee Push-Up" },
        ],
      },
      {
        title: "سیرکویت ۲",
        focus: "پا و قلب",
        exercises: [
          { name: "اسکیپ ردیف (Skater Jumps)", muscle: "پا و تعادل", sets: 4, reps: "14-18", restSec: 40, animKey: "Skater Jumps" },
          { name: "لانج پرشی (Plyo Lunge)", muscle: "پا", sets: 3, reps: "10-14", restSec: 45, animKey: "Plyo Lunge" },
          { name: "جک پرش (Jumping Jacks)", muscle: "هوازی", sets: 3, reps: "40s", restSec: 30, animKey: "Jumping Jacks" },
          { name: "پلانک پا باز (Plank Jack)", muscle: "مرکز بدن", sets: 3, reps: "16-20", restSec: 40, animKey: "Plank Jack" },
        ],
      },
      {
        title: "سیرکویت ۳",
        focus: "بالاتنه و شکم",
        exercises: [
          { name: "شنا (Push-Up)", muscle: "سینه", sets: 3, reps: "8-12", restSec: 45, animKey: "Push-Up" },
          { name: "اسپرینت درجا (High Knees)", muscle: "هوازی", sets: 4, reps: "25s", restSec: 35, animKey: "High Knees" },
          { name: "کرانچ دوچرخه (Bicycle Crunch)", muscle: "شکم", sets: 3, reps: "18-24", restSec: 40, animKey: "Bicycle Crunch" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "40s", restSec: 40, animKey: "Plank" },
        ],
      },
    ],
  },
  {
    slug: "w-calisthenics-30",
    gender: "women",
    title: "کالیستنیکس بانوان ۳۰ روزه",
    tagline: "قدرت با وزن بدن — زیبا و کاربردی",
    description:
      "شنا، بارفیکس کمکی، پلانک و لانج: مسیر ۳۰ روزهٔ قدرت با وزن بدن مخصوص بانوان — از نسخه‌های آسان شروع می‌شود و کم‌کم پیشرفته می‌شود.",
    disciplineLabel: "کالیستنیکس",
    difficulty: "beginner",
    durationDays: 30,
    daysPerWeek: 4,
    minutesPerDay: 30,
    equipment: "میلهٔ بارفیکس (اختیاری)",
    cover: "/images/challenges/women/w-calisthenics-30.jpg",
    accent: { from: "#10b981", via: "#059669", to: "#064e3b" },
    emoji: "🤸‍♀️",
    dayTemplates: [
      {
        title: "فشار با وزن بدن",
        focus: "سینه و بازو",
        exercises: [
          { name: "شنا زانو (Knee Push-Up)", muscle: "سینه", sets: 4, reps: "10-12", restSec: 45, animKey: "Knee Push-Up" },
          { name: "شنا (Push-Up)", muscle: "سینه", sets: 2, reps: "6-10", restSec: 60, animKey: "Push-Up" },
          { name: "شنا بالاسینه (Incline Push-Up)", muscle: "سینه", sets: 3, reps: "10-14", restSec: 45, animKey: "Incline Push-Up" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "35s", restSec: 40, animKey: "Plank" },
        ],
      },
      {
        title: "کشش با وزن بدن",
        focus: "پشت و جلو بازو",
        exercises: [
          { name: "بارفیکس با کمک کش (Band-Assisted Pull-Up)", muscle: "زیربغل", sets: 3, reps: "6-8", restSec: 90, animKey: "Band Assisted Pull-Up" },
          { name: "بارفیکس استرالیایی (Australian Pull-Up)", muscle: "زیربغل", sets: 3, reps: "8-12", restSec: 75, animKey: "Inverted Row" },
          { name: "جلو بازو دمبل (Dumbbell Bicep Curl)", muscle: "جلو بازو", sets: 3, reps: "10-12", restSec: 60, animKey: "Dumbbell Bicep Curl" },
          { name: "مرغ-سگ (Bird-Dog)", muscle: "ثبات تنه", sets: 3, reps: "10-12", restSec: 40, animKey: "Bird Dog" },
        ],
      },
      {
        title: "پا و مرکز بدن",
        focus: "پایین‌تنه",
        exercises: [
          { name: "اسکوات با وزن بدن (Bodyweight Squat)", muscle: "پا", sets: 4, reps: "15-20", restSec: 60, animKey: "Bodyweight Squat" },
          { name: "لانج معکوس (Reverse Lunge)", muscle: "پا", sets: 3, reps: "10-12", restSec: 60, animKey: "Reverse Lunge" },
          { name: "پل باسن (Glute Bridge)", muscle: "باسن", sets: 3, reps: "15-20", restSec: 45, animKey: "Glute Bridge" },
          { name: "پلانک جانبی (Side Plank)", muscle: "پهلو", sets: 3, reps: "20s", restSec: 40, animKey: "Side Plank" },
        ],
      },
    ],
  },
  {
    slug: "w-hiit-21",
    gender: "women",
    title: "HIIT چربی‌سوز بانوان",
    tagline: "۲۰ دقیقه در روز، چربی‌سوز ۲۴ ساعته",
    description:
      "بازه‌های شدت بالا مخصوص بانوان: ۲۰-۲۵ دقیقه تمرین که متابولیسم را تا ساعت‌ها بالا نگه می‌دارد. کوتاه، شدید، مؤثر — بدون فرصت خسته‌شدن.",
    disciplineLabel: "HIIT",
    difficulty: "intermediate",
    durationDays: 21,
    daysPerWeek: 5,
    minutesPerDay: 25,
    equipment: "بدون تجهیزات",
    cover: "/images/challenges/women/w-hiit-21.jpg",
    accent: { from: "#f43f5e", via: "#db2777", to: "#4c0519" },
    emoji: "🔥",
    dayTemplates: [
      {
        title: "HIIT فول‌بادی",
        focus: "چربی‌سوزی",
        exercises: [
          { name: "جک پرش (Jumping Jacks)", muscle: "هوازی", sets: 4, reps: "35s", restSec: 30, animKey: "Jumping Jacks" },
          { name: "برپی (Burpee)", muscle: "فول‌بادی", sets: 3, reps: "8-10", restSec: 45, animKey: "Burpee" },
          { name: "اسکوات پرشی (Jump Squat)", muscle: "پا", sets: 3, reps: "12-15", restSec: 45, animKey: "Jump Squat" },
          { name: "کوهنورد درجا (Mountain Climbers)", muscle: "شکم و هوازی", sets: 4, reps: "25s", restSec: 35, animKey: "Mountain Climbers" },
        ],
      },
      {
        title: "HIIT پایین‌تنه",
        focus: "پا و باسن",
        exercises: [
          { name: "اسکیپ ردیف (Skater Jumps)", muscle: "پا و تعادل", sets: 4, reps: "14-18", restSec: 40, animKey: "Skater Jumps" },
          { name: "لانج پرشی (Plyo Lunge)", muscle: "پا", sets: 3, reps: "10-12", restSec: 45, animKey: "Plyo Lunge" },
          { name: "اسکوات پرشی (Jump Squat)", muscle: "پا", sets: 3, reps: "12-15", restSec: 45, animKey: "Jump Squat" },
          { name: "پل باسن (Glute Bridge)", muscle: "باسن", sets: 3, reps: "15-20", restSec: 45, animKey: "Glute Bridge" },
        ],
      },
      {
        title: "HIIT شکم و بالاتنه",
        focus: "مرکز بدن",
        exercises: [
          { name: "شنا زانو (Knee Push-Up)", muscle: "سینه و بازو", sets: 3, reps: "10-12", restSec: 40, animKey: "Knee Push-Up" },
          { name: "اسپرینت درجا (High Knees)", muscle: "هوازی", sets: 4, reps: "25s", restSec: 35, animKey: "High Knees" },
          { name: "پلانک پا باز (Plank Jack)", muscle: "مرکز بدن", sets: 3, reps: "16-20", restSec: 40, animKey: "Plank Jack" },
          { name: "کرانچ دوچرخه (Bicycle Crunch)", muscle: "شکم", sets: 3, reps: "18-24", restSec: 40, animKey: "Bicycle Crunch" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 2, reps: "40s", restSec: 40, animKey: "Plank" },
        ],
      },
    ],
  },
  {
    slug: "w-functional-30",
    gender: "women",
    title: "فانکشنال بانوان ۳۰ روزه",
    tagline: "بدنی آماده برای زندگی واقعی",
    description:
      "حرکات کاربردی روزمره: حمل خرید، بچه برداشتن، خم‌شدن بدون کمردرد. قدرت کاربردی، تعادل و انعطاف — بدن کارآمد یعنی زندگی راحت‌تر.",
    disciplineLabel: "فانکشنال",
    difficulty: "beginner",
    durationDays: 30,
    daysPerWeek: 4,
    minutesPerDay: 30,
    equipment: "بدون تجهیزات",
    cover: "/images/challenges/women/w-functional-30.jpg",
    accent: { from: "#eab308", via: "#ca8a04", to: "#422006" },
    emoji: "🌿",
    dayTemplates: [
      {
        title: "الگوهای پایه",
        focus: "اسکوات و حمل",
        exercises: [
          { name: "اسکوات با وزن بدن (Bodyweight Squat)", muscle: "پا", sets: 3, reps: "15-18", restSec: 60, animKey: "Bodyweight Squat" },
          { name: "لانج معکوس (Reverse Lunge)", muscle: "پا", sets: 3, reps: "10-12", restSec: 60, animKey: "Reverse Lunge" },
          { name: "پل باسن (Glute Bridge)", muscle: "باسن", sets: 3, reps: "15-20", restSec: 45, animKey: "Glute Bridge" },
          { name: "قدم‌های بلند رو به جلو (Farmer March)", muscle: "تنه و گریپ", sets: 3, reps: "35s", restSec: 60, animKey: "Farmer March" },
        ],
      },
      {
        title: "بالاتنه کاربردی",
        focus: "فشار و کشش",
        exercises: [
          { name: "شنا زانو (Knee Push-Up)", muscle: "سینه و بازو", sets: 3, reps: "10-12", restSec: 45, animKey: "Knee Push-Up" },
          { name: "بارفیکس استرالیایی (Australian Pull-Up)", muscle: "پشت", sets: 3, reps: "8-10", restSec: 60, animKey: "Inverted Row" },
          { name: "پرس سرشانه دمبل (Dumbbell Shoulder Press)", muscle: "شانه", sets: 3, reps: "10-12", restSec: 60, animKey: "Dumbbell Shoulder Press" },
          { name: "مرغ-سگ (Bird-Dog)", muscle: "ثبات تنه", sets: 3, reps: "10-12", restSec: 40, animKey: "Bird Dog" },
        ],
      },
      {
        title: "تعادل و انعطاف",
        focus: "ثبات",
        exercises: [
          { name: "ترازوی تک‌پا (Single-Leg Balance)", muscle: "تعادل", sets: 3, reps: "25s", restSec: 40, animKey: "Single Leg Balance" },
          { name: "ددباگ (Dead Bug)", muscle: "مرکز بدن", sets: 3, reps: "12-14", restSec: 40, animKey: "Dead Bug" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "35s", restSec: 40, animKey: "Plank" },
          { name: "کشش گربه-شتر (Cat-Cow Stretch)", muscle: "ستون فقرات", sets: 2, reps: "10", restSec: 30, animKey: "Cat Cow" },
          { name: "کشش کودک (Child's Pose)", muscle: "ریلکس", sets: 1, reps: "45s", restSec: 30, animKey: "Child Pose" },
        ],
      },
    ],
  },
  {
    slug: "w-trx-21",
    gender: "women",
    title: "TRX بانوان ۲۱ روزه",
    tagline: "یک بند معلق، بدنی متفاوت",
    description:
      "تمرین معلق مخصوص بانوان: حمایت هوشمند بندها حرکات سخت را آسان و حرکات آسان را مؤثرتر می‌کند. فرم‌دهی کامل با یک بند TRX در خانه یا باشگاه.",
    disciplineLabel: "TRX",
    difficulty: "beginner",
    durationDays: 21,
    daysPerWeek: 4,
    minutesPerDay: 30,
    equipment: "بند TRX",
    cover: "/images/challenges/women/w-trx-21.jpg",
    accent: { from: "#14b8a6", via: "#0d9488", to: "#134e4a" },
    emoji: "🪢",
    dayTemplates: [
      {
        title: "TRX پایه",
        focus: "بالاتنه",
        exercises: [
          { name: "روئینگ TRX ایستاده (TRX Row)", muscle: "پشت", sets: 3, reps: "10-12", restSec: 60, animKey: "TRX Row" },
          { name: "پرس سینه TRX (TRX Chest Press)", muscle: "سینه", sets: 3, reps: "10-12", restSec: 60, animKey: "TRX Chest Press" },
          { name: "اسکوات TRX (TRX Squat)", muscle: "پا", sets: 3, reps: "12-15", restSec: 60, animKey: "TRX Squat" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "35s", restSec: 40, animKey: "Plank" },
        ],
      },
      {
        title: "TRX پیشرفته",
        focus: "کل بدن",
        exercises: [
          { name: "روئینگ TRX ایستاده (TRX Row)", muscle: "پشت", sets: 4, reps: "10-12", restSec: 60, animKey: "TRX Row" },
          { name: "پرس سینه TRX (TRX Chest Press)", muscle: "سینه", sets: 3, reps: "10-12", restSec: 60, animKey: "TRX Chest Press" },
          { name: "لانج TRX (TRX Lunge)", muscle: "پا", sets: 3, reps: "10-12", restSec: 60, animKey: "TRX Lunge" },
          { name: "پلانک TRX (TRX Plank)", muscle: "مرکز بدن", sets: 3, reps: "35s", restSec: 45, animKey: "TRX Plank" },
          { name: "کشش کودک (Child's Pose)", muscle: "ریلکس", sets: 1, reps: "45s", restSec: 30, animKey: "Child Pose" },
        ],
      },
    ],
  },
  {
    slug: "w-pilates-21",
    gender: "women",
    title: "پیلاتس فرم‌دهی ۲۱ روزه",
    tagline: "کشیده، خوش‌فرم، آرام — پیلاتس واقعی",
    description:
      "پیلاتس کلاسیک برای فرم بانوان: کشیدگی، مرکز بدن قوی و قامت مرتب. عضلات بلند و خوش‌فرم بدون حجم‌گیری — پرفروش‌ترین سبک تمرین بانوان جهان.",
    disciplineLabel: "پیلاتس",
    difficulty: "beginner",
    durationDays: 21,
    daysPerWeek: 4,
    minutesPerDay: 25,
    equipment: "مت تمرین",
    cover: "/images/challenges/women/w-pilates-21.jpg",
    accent: { from: "#a78bfa", via: "#8b5cf6", to: "#4c1d95" },
    emoji: "🧘‍♀️",
    dayTemplates: [
      {
        title: "پیلاتس پایه",
        focus: "مرکز بدن",
        exercises: [
          { name: "صد پیلاتس (Pilates Hundred)", muscle: "شکم", sets: 2, reps: "60s", restSec: 45, animKey: "Pilates Hundred" },
          { name: "رول‌آپ پیلاتس (Pilates Roll-Up)", muscle: "شکم و ستون", sets: 3, reps: "8-10", restSec: 45, animKey: "Pilates Roll Up" },
          { name: "پل باسن پیلاتس (Pilates Shoulder Bridge)", muscle: "باسن و کمر", sets: 3, reps: "10-12", restSec: 45, animKey: "Pilates Bridge" },
          { name: "پیلاتس باز و بسته کردن پاها (Single-Leg Stretch)", muscle: "شکم", sets: 3, reps: "12-16", restSec: 40, animKey: "Single Leg Stretch" },
        ],
      },
      {
        title: "پیلاتس و کشیدگی",
        focus: "فرم و انعطاف",
        exercises: [
          { name: "پیلاتس باز و بسته کردن پاها (Single-Leg Stretch)", muscle: "شکم", sets: 3, reps: "14-18", restSec: 40, animKey: "Single Leg Stretch" },
          { name: "پل جانبی لگن (Side-Lying Hip Abduction)", muscle: "باسن میانی", sets: 3, reps: "15-20", restSec: 40, animKey: "Side Hip Abduction" },
          { name: "پلانک جانبی (Side Plank)", muscle: "پهلو", sets: 3, reps: "25s", restSec: 45, animKey: "Side Plank" },
          { name: "چرخش ستون فقرات نشسته (Seated Spinal Twist)", muscle: "انعطاف", sets: 2, reps: "10", restSec: 30, animKey: "Seated Twist" },
          { name: "کشش کودک (Child's Pose)", muscle: "ریلکس", sets: 1, reps: "45s", restSec: 30, animKey: "Child Pose" },
        ],
      },
    ],
  },
  {
    slug: "w-balance-14",
    gender: "women",
    title: "تعادل و ثبات ۱۴ روزه",
    tagline: "۲ هفته ثبات — بدنی که مطمئن راه می‌رود",
    description:
      "چالش کوتاه تعادل: ثبات تک‌پا، مرکز بدن و هماهنگی. برای شروع مسیر تمرین عالی است و پیش‌نیاز امنی برای همهٔ چالش‌های بعدی.",
    disciplineLabel: "تعادل",
    difficulty: "beginner",
    durationDays: 14,
    daysPerWeek: 4,
    minutesPerDay: 20,
    equipment: "بدون تجهیزات",
    cover: "/images/challenges/women/w-balance-14.jpg",
    accent: { from: "#22d3ee", via: "#06b6d4", to: "#155e75" },
    emoji: "⚖️",
    dayTemplates: [
      {
        title: "تعادل پایه",
        focus: "ثبات ایستا",
        exercises: [
          { name: "ترازوی تک‌پا (Single-Leg Balance)", muscle: "تعادل", sets: 3, reps: "25s", restSec: 40, animKey: "Single Leg Balance" },
          { name: "مرغ-سگ (Bird-Dog)", muscle: "ثبات تنه", sets: 3, reps: "10-12", restSec: 40, animKey: "Bird Dog" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 3, reps: "35s", restSec: 40, animKey: "Plank" },
        ],
      },
      {
        title: "تعادل پویا",
        focus: "ثبات در حرکت",
        exercises: [
          { name: "اسکیپ ردیف (Skater Jumps)", muscle: "تعادل پویا", sets: 3, reps: "12-16", restSec: 45, animKey: "Skater Jumps" },
          { name: "لانج معکوس (Reverse Lunge)", muscle: "پا و تعادل", sets: 3, reps: "10-12", restSec: 60, animKey: "Reverse Lunge" },
          { name: "پلانک لمس شانه (Shoulder-Tap Plank)", muscle: "مرکز بدن", sets: 3, reps: "14-18", restSec: 45, animKey: "Plank Shoulder Tap" },
          { name: "ددباگ (Dead Bug)", muscle: "مرکز بدن", sets: 3, reps: "12-14", restSec: 40, animKey: "Dead Bug" },
        ],
      },
    ],
  },
  {
    slug: "w-fresh-start-14",
    gender: "women",
    title: "شروع دوباره بانوان ۱۴ روزه",
    tagline: "اولین قدم، قوی‌ترین قدم است",
    description:
      "همه‌چیز از اینجا شروع می‌شود: تمرین‌های ساده و ایمن در خانه، بدون تجهیزات. بدن آرام‌آرام فعال می‌شود و اعتماد به نفس ورزشی روزبه‌روز بالا می‌رود.",
    disciplineLabel: "شروع تمرین",
    difficulty: "beginner",
    durationDays: 14,
    daysPerWeek: 4,
    minutesPerDay: 20,
    equipment: "بدون تجهیزات — در خانه",
    cover: "/images/challenges/women/w-fresh-start-14.jpg",
    accent: { from: "#fb7185", via: "#f43f5e", to: "#881337" },
    emoji: "🌱",
    dayTemplates: [
      {
        title: "فعال‌سازی ملایم",
        focus: "شروع",
        exercises: [
          { name: "اسکوات با وزن بدن (Bodyweight Squat)", muscle: "پا", sets: 3, reps: "10-12", restSec: 60, animKey: "Bodyweight Squat" },
          { name: "شنا زانو (Knee Push-Up)", muscle: "سینه", sets: 3, reps: "8-10", restSec: 60, animKey: "Knee Push-Up" },
          { name: "پل باسن (Glute Bridge)", muscle: "باسن", sets: 3, reps: "12-15", restSec: 45, animKey: "Glute Bridge" },
          { name: "پلانک (Plank)", muscle: "مرکز بدن", sets: 2, reps: "25s", restSec: 40, animKey: "Plank" },
        ],
      },
      {
        title: "قلب و ریه سبک",
        focus: "هوازی ملایم",
        exercises: [
          { name: "جک پرش (Jumping Jacks)", muscle: "هوازی", sets: 3, reps: "25s", restSec: 45, animKey: "Jumping Jacks" },
          { name: "اسکوات سریع در جا (Fast Feet March)", muscle: "هوازی", sets: 3, reps: "30s", restSec: 45, animKey: "Fast Feet" },
          { name: "ددباگ (Dead Bug)", muscle: "مرکز بدن", sets: 3, reps: "10-12", restSec: 45, animKey: "Dead Bug" },
          { name: "کشش گربه-شتر (Cat-Cow Stretch)", muscle: "ستون فقرات", sets: 2, reps: "10", restSec: 30, animKey: "Cat Cow" },
          { name: "کشش کودک (Child's Pose)", muscle: "ریلکس", sets: 1, reps: "45s", restSec: 30, animKey: "Child Pose" },
        ],
      },
    ],
  },
  {
    slug: "w-posture-14",
    gender: "women",
    title: "اصلاح قوز و گردن ۱۴ روزه",
    tagline: "سر بالا، شانه‌ها عقب — قامت یک ملکه",
    description:
      "برای ساعت‌ها نشستن پشت میز و گوشی: تمرین‌های اصلاحی گردن، شانه و ستون فقرات. قامت درست = ظاهر کشیده‌تر، کمر سالم‌تر و اعتماد به نفس بیشتر.",
    disciplineLabel: "قامت و اصلاحی",
    difficulty: "beginner",
    durationDays: 14,
    daysPerWeek: 4,
    minutesPerDay: 15,
    equipment: "بدون تجهیزات",
    cover: "/images/challenges/women/w-posture-14.jpg",
    accent: { from: "#34d399", via: "#10b981", to: "#065f46" },
    emoji: "🦢",
    dayTemplates: [
      {
        title: "اصلاح قامت",
        focus: "گردن و شانه",
        exercises: [
          { name: "فرود بالانگل (Wall Angel)", muscle: "قامت", sets: 3, reps: "10-12", restSec: 45, animKey: "Wall Angel" },
          { name: "چین-تاک (Chin Tuck)", muscle: "گردن", sets: 3, reps: "10", restSec: 40 },
          { name: "اسپرانا (Reverse Fly)", muscle: "پشت شانه", sets: 3, reps: "12-15", restSec: 45, animKey: "Reverse Fly" },
          { name: "سوپرمن (Superman Hold)", muscle: "کمر", sets: 3, reps: "25s", restSec: 40, animKey: "Superman" },
        ],
      },
      {
        title: "باز کردن قفسهٔ سینه",
        focus: "انعطاف بالاتنه",
        exercises: [
          { name: "کشش دیواری سینه (Wall Chest Stretch)", muscle: "سینه", sets: 2, reps: "30s", restSec: 30, animKey: "Wall Chest Stretch" },
          { name: "کشش کبرا (Cobra Stretch)", muscle: "شکم و سینه", sets: 2, reps: "25s", restSec: 40, animKey: "Cobra Stretch" },
          { name: "مرغ-سگ (Bird-Dog)", muscle: "ثبات تنه", sets: 3, reps: "10-12", restSec: 40, animKey: "Bird Dog" },
          { name: "کشش گربه-شتر (Cat-Cow Stretch)", muscle: "ستون فقرات", sets: 2, reps: "10", restSec: 30, animKey: "Cat Cow" },
        ],
      },
    ],
  },
];
