/**
 * challenge-videos.ts — نقشهٔ ویدیوهای Muscle Wiki چالش‌ها (تولید خودکار — v189)
 *
 * منبع: research/musclewiki/prepared.json ← scripts/mw-prepare-videos.mjs
 * کلید = نام انگلیسی دقیق حرکت (همان که داخل پرانتز نام فارسی چالش‌هاست)
 * مقدار = مسیر وب ویدیوی فشرده‌شدهٔ ۷۲۰p (زیر ۱ مگابایت) برای هر جنسیت
 * حرکاتِ بدون ورودی = ویدیوی مناسب ندارند → جلسه به انیمیشن دوفریمی برمی‌گردد.
 */

export interface ChallengeVideoEntry {
  m?: string; // مسیر ویدیوی مرد
  f?: string; // مسیر ویدیوی زن
}

export const CHALLENGE_VIDEOS: Record<string, ChallengeVideoEntry> = {
  "Ab Wheel Rollout": { m: "/videos/challenges/male/ab-wheel-rollout.mp4", f: "/videos/challenges/female/ab-wheel-rollout.mp4" },
  "Archer Push-Up": { m: "/videos/challenges/male/archer-push-up.mp4", f: "/videos/challenges/female/archer-push-up.mp4" },
  "Australian Pull-Up": { m: "/videos/challenges/male/australian-pull-up.mp4", f: "/videos/challenges/female/australian-pull-up.mp4" },
  "Band-Assisted Pull-Up": { m: "/videos/challenges/male/band-assisted-pull-up.mp4", f: "/videos/challenges/female/band-assisted-pull-up.mp4" },
  "Barbell Back Squat": { m: "/videos/challenges/male/barbell-back-squat.mp4", f: "/videos/challenges/female/barbell-back-squat.mp4" },
  "Barbell Bench Press": { m: "/videos/challenges/male/barbell-bench-press.mp4", f: "/videos/challenges/female/barbell-bench-press.mp4" },
  "Barbell Bicep Curl": { m: "/videos/challenges/male/barbell-bicep-curl.mp4", f: "/videos/challenges/female/barbell-bicep-curl.mp4" },
  "Barbell Deadlift": { m: "/videos/challenges/male/barbell-deadlift.mp4", f: "/videos/challenges/female/barbell-deadlift.mp4" },
  "Barbell Shoulder Press": { m: "/videos/challenges/male/barbell-shoulder-press.mp4", f: "/videos/challenges/female/barbell-shoulder-press.mp4" },
  "Bent-Over Barbell Row": { m: "/videos/challenges/male/bent-over-barbell-row.mp4", f: "/videos/challenges/female/bent-over-barbell-row.mp4" },
  "Bicycle Crunch": { m: "/videos/challenges/male/bicycle-crunch.mp4", f: "/videos/challenges/female/bicycle-crunch.mp4" },
  "Bird-Dog": { m: "/videos/challenges/male/bird-dog.mp4", f: "/videos/challenges/female/bird-dog.mp4" },
  "Bodyweight Squat": { m: "/videos/challenges/male/bodyweight-squat.mp4", f: "/videos/challenges/female/bodyweight-squat.mp4" },
  "Bulgarian Split Squat": { m: "/videos/challenges/male/bulgarian-split-squat.mp4", f: "/videos/challenges/female/bulgarian-split-squat.mp4" },
  "Burpee": { m: "/videos/challenges/male/burpee.mp4", f: "/videos/challenges/female/burpee.mp4" },
  "Calf Stretch": { m: "/videos/challenges/male/calf-stretch.mp4", f: "/videos/challenges/female/calf-stretch.mp4" },
  "Cat-Cow Stretch": { m: "/videos/challenges/male/cat-cow-stretch.mp4", f: "/videos/challenges/female/cat-cow-stretch.mp4" },
  "Child's Pose": { m: "/videos/challenges/male/child-s-pose.mp4", f: "/videos/challenges/female/child-s-pose.mp4" },
  "Clamshell": { m: "/videos/challenges/male/clamshell.mp4", f: "/videos/challenges/female/clamshell.mp4" },
  "Clap Push-Up": { m: "/videos/challenges/male/clap-push-up.mp4", f: "/videos/challenges/female/clap-push-up.mp4" },
  "Cobra Stretch": { m: "/videos/challenges/male/cobra-stretch.mp4", f: "/videos/challenges/female/cobra-stretch.mp4" },
  "Crunch": { m: "/videos/challenges/male/crunch.mp4", f: "/videos/challenges/female/crunch.mp4" },
  "Dead Bug": { m: "/videos/challenges/male/dead-bug.mp4", f: "/videos/challenges/female/dead-bug.mp4" },
  "Diamond Push-Up": { m: "/videos/challenges/male/diamond-push-up.mp4", f: "/videos/challenges/female/diamond-push-up.mp4" },
  "Dips": { m: "/videos/challenges/male/dips.mp4", f: "/videos/challenges/female/dips.mp4" },
  "Dumbbell Bench Press": { m: "/videos/challenges/male/dumbbell-bench-press.mp4" },
  "Dumbbell Bicep Curl": { m: "/videos/challenges/male/dumbbell-bicep-curl.mp4", f: "/videos/challenges/female/dumbbell-bicep-curl.mp4" },
  "Dumbbell Front Raise": { m: "/videos/challenges/male/dumbbell-front-raise.mp4", f: "/videos/challenges/female/dumbbell-front-raise.mp4" },
  "Dumbbell Lateral Raise": { m: "/videos/challenges/male/dumbbell-lateral-raise.mp4", f: "/videos/challenges/female/dumbbell-lateral-raise.mp4" },
  "Dumbbell Pullover": { m: "/videos/challenges/male/dumbbell-pullover.mp4", f: "/videos/challenges/female/dumbbell-pullover.mp4" },
  "Dumbbell Romanian Deadlift": { m: "/videos/challenges/male/dumbbell-romanian-deadlift.mp4", f: "/videos/challenges/female/dumbbell-romanian-deadlift.mp4" },
  "Dumbbell Shoulder Press": { m: "/videos/challenges/male/dumbbell-shoulder-press.mp4", f: "/videos/challenges/female/dumbbell-shoulder-press.mp4" },
  "Dumbbell Shrug": { m: "/videos/challenges/male/dumbbell-shrug.mp4", f: "/videos/challenges/female/dumbbell-shrug.mp4" },
  "Face Pull": { m: "/videos/challenges/male/face-pull.mp4", f: "/videos/challenges/female/face-pull.mp4" },
  "Farmer March": { m: "/videos/challenges/male/farmer-march.mp4", f: "/videos/challenges/female/farmer-march.mp4" },
  "Fast Feet March": { m: "/videos/challenges/male/fast-feet-march.mp4", f: "/videos/challenges/female/fast-feet-march.mp4" },
  "Glute Bridge": { m: "/videos/challenges/male/glute-bridge.mp4", f: "/videos/challenges/female/glute-bridge.mp4" },
  "Glute Kickback": { m: "/videos/challenges/male/glute-kickback.mp4", f: "/videos/challenges/female/glute-kickback.mp4" },
  "Goblet Squat": { m: "/videos/challenges/male/goblet-squat.mp4", f: "/videos/challenges/female/goblet-squat.mp4" },
  "Hammer Curl": { m: "/videos/challenges/male/hammer-curl.mp4", f: "/videos/challenges/female/hammer-curl.mp4" },
  "Hanging Leg Raise": { m: "/videos/challenges/male/hanging-leg-raise.mp4", f: "/videos/challenges/female/hanging-leg-raise.mp4" },
  "High Knees": { m: "/videos/challenges/male/high-knees.mp4", f: "/videos/challenges/female/high-knees.mp4" },
  "Hip Thrust": { m: "/videos/challenges/male/hip-thrust.mp4", f: "/videos/challenges/female/hip-thrust.mp4" },
  "Incline Push-Up": { m: "/videos/challenges/male/incline-push-up.mp4", f: "/videos/challenges/female/incline-push-up.mp4" },
  "Jump Squat": { m: "/videos/challenges/male/jump-squat.mp4", f: "/videos/challenges/female/jump-squat.mp4" },
  "Jumping Jacks": { m: "/videos/challenges/male/jumping-jacks.mp4", f: "/videos/challenges/female/jumping-jacks.mp4" },
  "Knee Push-Up": { m: "/videos/challenges/male/knee-push-up.mp4", f: "/videos/challenges/female/knee-push-up.mp4" },
  "Lat Pulldown": { m: "/videos/challenges/male/lat-pulldown.mp4", f: "/videos/challenges/female/lat-pulldown.mp4" },
  "Leg Raise": { m: "/videos/challenges/male/leg-raise.mp4", f: "/videos/challenges/female/leg-raise.mp4" },
  "Lunge": { m: "/videos/challenges/male/lunge.mp4", f: "/videos/challenges/female/lunge.mp4" },
  "Mountain Climbers": { m: "/videos/challenges/male/mountain-climbers.mp4", f: "/videos/challenges/female/mountain-climbers.mp4" },
  "Overhead Dumbbell Extension": { m: "/videos/challenges/male/overhead-dumbbell-extension.mp4", f: "/videos/challenges/female/overhead-dumbbell-extension.mp4" },
  "Pilates Hundred": { m: "/videos/challenges/male/pilates-hundred.mp4", f: "/videos/challenges/female/pilates-hundred.mp4" },
  "Pilates Shoulder Bridge": { m: "/videos/challenges/male/pilates-shoulder-bridge.mp4", f: "/videos/challenges/female/pilates-shoulder-bridge.mp4" },
  "Plank": { m: "/videos/challenges/male/plank.mp4", f: "/videos/challenges/female/plank.mp4" },
  "Plank Jack": { m: "/videos/challenges/male/plank-jack.mp4", f: "/videos/challenges/female/plank-jack.mp4" },
  "Plank Up-Down": { m: "/videos/challenges/male/plank-up-down.mp4", f: "/videos/challenges/female/plank-up-down.mp4" },
  "Plyo Lunge": { m: "/videos/challenges/male/plyo-lunge.mp4", f: "/videos/challenges/female/plyo-lunge.mp4" },
  "Pull-Up": { m: "/videos/challenges/male/pull-up.mp4", f: "/videos/challenges/female/pull-up.mp4" },
  "Push-Up": { m: "/videos/challenges/male/push-up.mp4", f: "/videos/challenges/female/push-up.mp4" },
  "Reverse Fly": { m: "/videos/challenges/male/reverse-fly.mp4", f: "/videos/challenges/female/reverse-fly.mp4" },
  "Reverse Lunge": { m: "/videos/challenges/male/reverse-lunge.mp4", f: "/videos/challenges/female/reverse-lunge.mp4" },
  "Romanian Deadlift": { m: "/videos/challenges/male/romanian-deadlift.mp4", f: "/videos/challenges/female/romanian-deadlift.mp4" },
  "Russian Twist": { m: "/videos/challenges/male/russian-twist.mp4", f: "/videos/challenges/female/russian-twist.mp4" },
  "Scissor Kicks": { m: "/videos/challenges/male/scissor-kicks.mp4", f: "/videos/challenges/female/scissor-kicks.mp4" },
  "Seated Spinal Twist": { m: "/videos/challenges/male/seated-spinal-twist.mp4", f: "/videos/challenges/female/seated-spinal-twist.mp4" },
  "Shoulder-Tap Plank": { m: "/videos/challenges/male/shoulder-tap-plank.mp4", f: "/videos/challenges/female/shoulder-tap-plank.mp4" },
  "Side Lunge": { m: "/videos/challenges/male/side-lunge.mp4", f: "/videos/challenges/female/side-lunge.mp4" },
  "Side Plank": { m: "/videos/challenges/male/side-plank.mp4", f: "/videos/challenges/female/side-plank.mp4" },
  "Side-Lying Hip Abduction": { m: "/videos/challenges/male/side-lying-hip-abduction.mp4", f: "/videos/challenges/female/side-lying-hip-abduction.mp4" },
  "Single-Arm Dumbbell Row": { m: "/videos/challenges/male/single-arm-dumbbell-row.mp4", f: "/videos/challenges/female/single-arm-dumbbell-row.mp4" },
  "Single-Leg Balance": { m: "/videos/challenges/male/single-leg-balance.mp4", f: "/videos/challenges/female/single-leg-balance.mp4" },
  "Single-Leg Glute Bridge": { m: "/videos/challenges/male/single-leg-glute-bridge.mp4", f: "/videos/challenges/female/single-leg-glute-bridge.mp4" },
  "Skater Jumps": { m: "/videos/challenges/male/skater-jumps.mp4", f: "/videos/challenges/female/skater-jumps.mp4" },
  "Standing Calf Raise": { m: "/videos/challenges/male/standing-calf-raise.mp4", f: "/videos/challenges/female/standing-calf-raise.mp4" },
  "Star Jump Squat": { m: "/videos/challenges/male/star-jump-squat.mp4", f: "/videos/challenges/female/star-jump-squat.mp4" },
  "Superman Hold": { m: "/videos/challenges/male/superman-hold.mp4", f: "/videos/challenges/female/superman-hold.mp4" },
  "Triceps Pushdown": { m: "/videos/challenges/male/triceps-pushdown.mp4", f: "/videos/challenges/female/triceps-pushdown.mp4" },
  "TRX Chest Press": { m: "/videos/challenges/male/trx-chest-press.mp4", f: "/videos/challenges/female/trx-chest-press.mp4" },
  "TRX Lunge": { m: "/videos/challenges/male/trx-lunge.mp4", f: "/videos/challenges/female/trx-lunge.mp4" },
  "TRX Plank": { m: "/videos/challenges/male/trx-plank.mp4", f: "/videos/challenges/female/trx-plank.mp4" },
  "TRX Row": { m: "/videos/challenges/male/trx-row.mp4", f: "/videos/challenges/female/trx-row.mp4" },
  "TRX Squat": { m: "/videos/challenges/male/trx-squat.mp4", f: "/videos/challenges/female/trx-squat.mp4" },
  "Wall Angel": { m: "/videos/challenges/male/wall-angel.mp4", f: "/videos/challenges/female/wall-angel.mp4" },
  "Wall Chest Stretch": { m: "/videos/challenges/male/wall-chest-stretch.mp4", f: "/videos/challenges/female/wall-chest-stretch.mp4" },
  "Wide Push-Up": { m: "/videos/challenges/male/wide-push-up.mp4", f: "/videos/challenges/female/wide-push-up.mp4" },
};

// 86 حرکت با ویدیو از 90 حرکت چالش
