import { chromium, devices } from "playwright";
import { createHash } from "crypto";
import { PrismaClient } from "@prisma/client";
const BASE = "http://localhost:3000";
const MOBILE = "09350002338";
const OTP = "2141";
const prisma = new PrismaClient();
let u = await prisma.user.findUnique({ where: { mobile: MOBILE } });
if (!u) u = await prisma.user.create({ data: { mobile: MOBILE, name: "ب۲" } });
await prisma.user.update({ where: { id: u.id }, data: { onboardingDone: false } });
await prisma.otpCode.deleteMany({ where: { mobile: MOBILE } });
await prisma.otpCode.create({ data: { mobile: MOBILE, code: createHash("sha256").update(`fitup-otp:${OTP}`).digest("hex"), expiresAt: new Date(Date.now() + 600000), used: false } });
const r = await fetch(`${BASE}/api/auth/verify-otp`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mobile: MOBILE, code: OTP }), redirect: "manual" });
const ck = (r.headers.get("set-cookie") || "").match(/sc_session=([^;]+)/)?.[1];
const browser = await chromium.launch();
const ctx = await browser.newContext({ ...devices["Pixel 7"], locale: "fa-IR" });
await ctx.addCookies([{ name: "sc_session", value: ck, url: BASE }]);
const page = await ctx.newPage();
await page.goto(`${BASE}/?screen=auth`, { waitUntil: "domcontentloaded" });
await page.waitForSelector('input[placeholder="۱۷۵"]', { timeout: 25000 });
await page.waitForTimeout(2000);
const out = await page.evaluate(async () => {
  const sleep = (ms) => new Promise((r2) => setTimeout(r2, ms));
  let sc = document.querySelector("[data-onb-q]");
  while (sc && !/auto|scroll/.test(getComputedStyle(sc).overflowY)) sc = sc.parentElement;
  let fakeH = window.innerHeight;
  Object.defineProperty(window, "innerHeight", { configurable: true, get: () => fakeH });
  const vv = window.visualViewport;
  const realVvH = vv.height;
  const input = document.querySelector('input[placeholder="۱۷۵"]');
  sc.scrollTop = 40;
  await sleep(80);
  input.focus();
  await sleep(60);
  fakeH = realVvH + 420;
  await sleep(60);
  sc.scrollTop = 612;
  await sleep(2500);
  const drifted = sc.scrollTop;
  fakeH = realVvH;
  vv.dispatchEvent(new Event("resize"));
  input.blur();
  await sleep(1200);
  return { drifted, finalTop: sc.scrollTop, kbdbg3: window.__kbdbg3 || [] };
});
console.log(JSON.stringify(out, null, 1));
await browser.close();
process.exit(0);
